**Lab 1**
1. Use git init to create an empty repo
2. Add a file to local repo and push to github
3. Make additional changes to same file, again push to github
4. Add a collaborator to your repo
5. Ask you collaborator to make change to the file and push to repo
6. You try to make a diff change at the same place in the file and push to repo
7. Step6 will fail, Fix merge conflicts and push again
8. Verify all the commits in github
9. Revert code to previous version


**Lab 2**
1. Remove push access to master branch from your collabortator
2. Ask your collaborator to create a new branch
3. Push new code changes to that branch
4. Create a pull request from that branch to master branch
5. Approve and merge the pull request
6. Do a git pull and veirfy that you can see the new changes in master branch


**Lab 3**
1. Use python requests to post a comment on your commit
2. Use python requests to find top 10 commiters on django repo

In [0]:
import requests
r=requests.get("http://iitk.ac.in/")
#print(r.headers)
print(r.status_code)

{'Date': 'Sun, 10 Nov 2019 09:09:30 GMT', 'Server': 'Apache', 'Set-Cookie': 'd8fdb0c7bbb290989fe5b71584d38355=mau880ok4dkm75l1h865j360i7; path=/', 'P3P': 'CP="NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM"', 'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Connection': 'close', 'Transfer-Encoding': 'chunked', 'Content-Type': 'text/html; charset=utf-8'}


In [0]:
import requests
import pprint
headers = {'Authorization': 'token '}
json = {'body': 'comment from api call','path':'index.html'}
r= requests.get('https://api.github.com/repos/Akshay-31/SirusT/commits/47580f8615716615c8dd98fb5e2be172d45e37cb/',headers=headers,json=json)
pprint.pprint(r.json())


{'documentation_url': 'https://developer.github.com/v3/repos/commits/#get-a-single-commit',
 'message': 'No commit found for SHA: '
            '47580f8615716615c8dd98fb5e2be172d45e37cb/'}


**Lab 4**
1. Create a 8x8x8 array with random values
2. From the matrix in (1) Negate all elements
whose values are between 3 to 8
3. Multiply a 8x3 matrix by 3x2 matrix and
prints the columns as 1 D array

In [0]:
import numpy as np
a=np.random.randint(1,10,(8,8,8))
print(a)

In [0]:
import numpy as np
a=np.random.randint(1,10,(8,8,8))
print(a)
m = (a > 3) & (a < 8) #Filters the elements and returns index satisfying given condition
a[m] *= -1
print(a)

In [0]:
import numpy as np
a=np.random.randint(2,5,(8,3))
b=np.random.randint(2,5,(3,2))
c=np.dot(a,b)
print(a)
print(b)
c.reshape(1,16)


**Lab 5**

1. Create a 8x8x8 matrix with random values ranging from 5 to 9
2. Find the diagonal of product of two random 5x5 matrices
3. Negate a boolean, or to change the the sign of the float inplace

In [0]:
import numpy as np
a=np.random.randint(5,9,(8,8,8))
print(a)

In [0]:
import numpy as np
a=np.random.randint(1,5,(5,5))
b=np.random.randint(1,5,(5,5))
c=np.matmul(a,b)
print(c)
np.diagonal(c)

[[29 19 24 37 23]
 [28 23 28 41 24]
 [54 36 40 64 46]
 [24 15 19 30 18]
 [31 24 22 38 29]]


array([29, 23, 40, 30, 29])

In [0]:
x=np.arange(5)
np.logical_not(x<3)


array([False, False, False,  True,  True])

In [0]:
y=np.random.rand(5,5)
np.logical_not(y<1)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

**Lab 6**

Given 100 random points in 2D space and find the top 10 closest points to the origin.

In [0]:
c=np.random.randn(100,2)
dist=np.sqrt(c[:,0]**2+c[:,1]**2)
top_10=np.argsort(dist)[:10]
print(c[top_10])

[[-0.07877606  0.17109243]
 [-0.20613387 -0.03944061]
 [ 0.34920788  0.06532327]
 [-0.37141447  0.03721416]
 [ 0.34762497  0.17763628]
 [-0.37322331 -0.16752851]
 [-0.2712373   0.36290963]
 [ 0.45463438  0.02072811]
 [-0.33244914  0.33148182]
 [-0.39503622 -0.26376318]]


**Lab 7**

Find the value of pi using Monte Carlo simulation.

**Hint:-** 

Consider a unit circle which is enclosed in a square. randomly genrate uniformily distributed points inside the square. The fraction of points falling inside the circle is pi/4. 

In [0]:
import random as r
import math as m
inside = 0
total = 1000
# Iterate for the number of points.
for i in range(0, total):
  x2 = r.random()**2
  y2 = r.random()**2
  if m.sqrt(x2 + y2) < 1.0:
    inside += 1
pi = (float(inside) / total) * 4
print(pi)
error=(3.14-pi)/3.14
print("Error =",error*100,"%")


3.124
Error = 0.509554140127389 %


**Home Work**

1. wap the first two rows of a random 5x5
array
2. How to get the block-sum of a 16x16 matrix
(block size is 4x4)?
3. Sort an array by the nth column
4. Subtract the mean of each row of a matrix
from each element

In [0]:
# Wap the first two rows of a random 5x5 array
a=np.random.rand(4,4)
a[:2,]

array([[0.2755294 , 0.83306949, 0.35730537, 0.3903362 ],
       [0.73792976, 0.50751356, 0.63986814, 0.02803128]])

In [0]:
a=np.ones((16,16),dtype=np.int16)
b1=a[:4,:4].sum()
b2=a[4:8,:4].sum()
b3=a[8:12,:4].sum()
b4=a[12:16,:4].sum()
b5=a[:4,4:8].sum()
b6=a[4:8,4:8].sum()
b7=a[8:12,4:8].sum()
b8=a[12:16,4:8].sum()
b9=a[:4,8:12].sum()
b10=a[4:8,8:12].sum()
b11=a[8:12,8:12].sum()
b12=a[12:16,8:12].sum()
b13=a[:4,12:16].sum()
b14=a[4:8,12:16].sum()
b15=a[8:12,12:16].sum()
b16=a[12:16,12:16].sum()
print(b1,b2,b3,b4)
print(b5,b6,b7,b8)
print(b9,b10,b11,b12)
print(b13,b14,b15,b16)

16 16 16 16
16 16 16 16
16 16 16 16
16 16 16 16


In [13]:
import numpy as np
a=np.random.randint(1,10,(5,5))
a[:,:4].sort()
print(a)

[[1 2 2 6 3]
 [1 3 6 9 6]
 [2 4 6 8 3]
 [1 3 6 8 2]
 [2 6 7 7 8]]


In [17]:
#Subtract the mean of each row of a matrix from each element
import numpy as np
a=np.random.rand(5,5)
print(a)
a[:1,]=a[:1,]-a[:1,].mean()
a[1:2,]=a[1:2,]-a[1:2,].mean()
a[2:3,]=a[2:3,]-a[2:3,].mean()
a[3:4,]=a[3:4,]-a[3:4,].mean()
a[4:5,]=a[4:5,]-a[4:5,].mean()
print(a)

[[0.24451363 0.54497438 0.11615057 0.2169071  0.7650392 ]
 [0.31903824 0.04133216 0.51019755 0.2268079  0.95289092]
 [0.32721058 0.64665664 0.27563959 0.99660308 0.96920881]
 [0.46673928 0.56423111 0.03822911 0.99516593 0.91060692]
 [0.363456   0.07267563 0.9486287  0.46770902 0.7110326 ]]
[[-0.13300335  0.1674574  -0.2613664  -0.16060988  0.38752223]
 [-0.09101512 -0.36872119  0.1001442  -0.18324545  0.54283757]
 [-0.31585316  0.0035929  -0.36742415  0.35353934  0.32614507]
 [-0.12825519 -0.03076336 -0.55676536  0.40017146  0.31561245]
 [ 0.363456    0.07267563  0.9486287   0.46770902  0.7110326 ]]
