**Lab 1**
1. Use git init to create an empty repo
2. Add a file to local repo and push to github
3. Make additional changes to same file, again push to github
4. Add a collaborator to your repo
5. Ask you collaborator to make change to the file and push to repo
6. You try to make a diff change at the same place in the file and push to repo
7. Step6 will fail, Fix merge conflicts and push again
8. Verify all the commits in github
9. Revert code to previous version


In [0]:
# 1.Use git init to create an empty repo
git init [repository name]

**Lab 2**
1. Remove push access to master branch from your collabortator
2. Ask your collaborator to create a new branch
3. Push new code changes to that branch
4. Create a pull request from that branch to master branch
5. Approve and merge the pull request
6. Do a git pull and veirfy that you can see the new changes in master branch


**Lab 3**
1. Use python requests to post a comment on your commit
2. Use python requests to find top 10 commiters on django repo

In [0]:
# 1.Use python requests to post a comment on your commit
import requests
import pprint
headers = {'Authorization':'token 01bde65951e4bc5c4487d26c822cf0883647e88b '}
json={'body':'comment from api call','path':'index.html'}
r=requests.post('https://api.github.com/repos/ankushkumarddm@gmail.com/day2/commits/bf0e7d22eab657d165ee8a1a7008a9f720b385fe/comments',headers=headers,json=json)
pprint.pprint(r.json()) 

In [0]:
# 2.Use python requests to find top 10 commiters on django repo


**Lab 4**
1. Create a 8x8x8 array with random values
2. From the matrix in (1) Negate all elements
whose values are between 3 to 8
3. Multiply a 8x3 matrix by 3x2 matrix and
prints the columns as 1 D array

In [0]:
# 1.Create a 8x8x8 array with random values
import numpy as np
x = np.random.randint(1,10,(8,8,8))
print(x)


[[[1 2 7 7 5 9 1 9]
  [7 8 8 9 3 9 2 1]
  [4 7 3 2 6 8 1 3]
  [4 3 9 1 9 1 1 7]
  [2 9 7 2 1 5 9 5]
  [2 3 6 6 9 7 9 5]
  [6 1 4 1 7 1 5 2]
  [2 9 7 3 4 8 9 5]]

 [[5 8 6 5 8 5 4 5]
  [8 4 4 3 3 5 9 5]
  [4 9 6 2 8 6 5 1]
  [7 4 3 1 1 3 4 8]
  [5 3 9 7 1 8 1 2]
  [6 2 3 4 2 2 8 6]
  [1 3 4 7 2 9 8 3]
  [7 1 2 2 6 6 2 8]]

 [[4 9 2 4 6 8 7 3]
  [6 8 3 9 6 6 3 5]
  [7 4 1 5 7 3 1 2]
  [3 6 6 7 9 7 3 5]
  [8 8 2 1 5 9 4 4]
  [5 5 1 5 9 8 7 3]
  [5 5 3 3 5 7 9 9]
  [9 8 5 1 6 9 6 2]]

 [[8 6 8 8 6 6 4 3]
  [2 2 3 4 4 7 4 3]
  [6 2 9 2 1 3 1 8]
  [2 3 6 7 3 2 6 7]
  [3 8 2 1 8 5 6 6]
  [7 3 7 6 2 7 4 4]
  [6 8 7 4 5 9 3 4]
  [2 1 7 3 9 2 8 1]]

 [[4 4 5 9 1 7 3 3]
  [1 5 1 3 4 3 7 3]
  [5 2 6 5 1 6 3 1]
  [7 8 9 8 9 3 3 8]
  [7 7 4 9 3 5 8 3]
  [2 2 5 1 5 6 5 8]
  [4 4 7 7 6 9 5 7]
  [1 9 5 5 8 4 9 7]]

 [[7 8 1 2 4 4 5 3]
  [3 5 1 6 2 9 2 4]
  [2 6 1 6 5 6 7 9]
  [1 2 7 9 6 8 8 5]
  [9 9 1 3 3 8 9 8]
  [2 4 6 6 2 5 7 1]
  [3 1 2 3 4 3 3 8]
  [2 2 7 8 8 9 2 6]]

 [[3 4 9 9 3 6 2 5]
  [3 5 4

In [0]:
# 2.From the matrix in [1] Negate all elements whose values are between 3 to 8
import numpy as np
x = np.random.randint(1,10,(8,8,8))
mask=(x>3)&(x<8)
x[mask]=-1*x[mask]
print(x)

[[[-6  1  3  9 -7  2 -6  2]
  [-5  3  1 -4  8 -4  9 -6]
  [ 1 -5 -4  9 -6  2  9  1]
  [-4  3  9 -4 -6  1 -7  1]
  [ 1  9 -7 -4 -5 -6  1 -5]
  [ 1  1  1 -7 -7 -5  8 -5]
  [-5  8  3 -4 -4  2  3 -7]
  [ 3  3  9 -7  3 -6  2  2]]

 [[ 3  1 -4  3  1 -5  2 -5]
  [ 9  1  1  9 -7 -7  2  2]
  [ 8  1 -4  8 -4  1  1  9]
  [ 2  2 -5 -5  2  3  9  9]
  [ 8  9  8  2  2  1  8  3]
  [ 8 -4  3  8  8 -4  2 -6]
  [ 9  3 -5 -4 -5  9  3  9]
  [-4 -7  3  2  9  3  8 -7]]

 [[ 3 -6 -5  3 -5 -6  2  8]
  [ 1  8  3  9  3 -5  2  2]
  [ 2 -4  3 -7  8 -6  1  3]
  [-7 -5  2 -6 -6  3 -5  2]
  [-4 -7  2 -5 -4  8  9 -4]
  [ 3 -4 -7 -4 -4  1  1  9]
  [-7 -4 -7 -7 -7  8  1  3]
  [ 3  3  1 -6  3  2  8 -6]]

 [[-6  3  2  3  3  2  2  9]
  [-4  1  3  2  9  2 -4  3]
  [ 8  9 -5 -7 -5 -5 -7 -6]
  [-7  3 -6  8  8  3  2 -7]
  [ 9 -5 -6  3  9  9 -5  3]
  [ 1  1  9  1  1  2 -4  1]
  [ 2 -5  9 -7 -4 -4 -7  9]
  [ 1  9  2 -6 -7 -5  3 -6]]

 [[ 2  3  2 -5  2 -6  3  3]
  [-5 -6  2  2 -4  2 -6  3]
  [ 9 -5 -6  8 -7  8  1  2]
  [ 2 -4  2 

In [0]:
# 3.Multiply a 8x3 matrix by 3x2 matrix and prints the columns as 1 D array
import numpy as np   
x = np.random.randint(1,5,(8,3))
y = np.random.randint(1,5,(3,2))
res = np.dot(x,y) 
# print resulted matrix 
new_res=res.reshape(1,16)
print(new_res)

[[21 20 16 22 17 17  7  9 21 26 21 23 14 18 20 29]]


**Lab 5**

1. Create a 8x8x8 matrix with random values ranging from 5 to 9
2. Find the diagonal of product of two random 5x5 matrices
3. Negate a boolean, or to change the the sign of the float inplace

In [0]:
# 1.Create a 8x8x8 matrix with random values ranging from 5 to 9
import numpy as np
x = np.random.randint(5,9,(8,8,8))
print(x)

[[[8 5 7 8 8 7 8 8]
  [7 8 6 8 6 6 5 5]
  [8 7 8 8 5 6 5 5]
  [6 8 7 7 7 5 7 8]
  [7 8 6 5 7 8 5 6]
  [8 8 7 5 7 5 5 5]
  [5 6 7 7 7 7 7 8]
  [8 8 5 7 7 7 8 8]]

 [[8 7 5 8 7 6 6 6]
  [7 8 6 7 6 6 7 7]
  [6 7 6 8 8 7 8 7]
  [8 7 8 8 7 6 6 7]
  [5 6 7 7 7 5 7 7]
  [8 6 6 6 6 5 6 6]
  [5 6 8 7 7 6 5 8]
  [6 8 5 5 7 8 5 5]]

 [[7 6 7 7 5 7 6 6]
  [6 7 8 5 7 8 5 8]
  [8 5 8 6 8 8 6 6]
  [5 6 8 5 6 8 8 8]
  [5 5 5 5 5 6 8 6]
  [7 7 7 7 6 8 5 5]
  [8 6 5 5 8 5 5 5]
  [7 6 6 6 5 7 7 8]]

 [[8 7 6 6 5 7 8 7]
  [6 7 8 6 6 5 5 5]
  [5 7 8 6 5 6 6 5]
  [5 6 7 7 8 5 5 5]
  [8 5 5 8 5 8 6 6]
  [8 5 6 7 8 5 6 5]
  [7 6 5 8 6 6 6 8]
  [8 6 5 7 6 6 7 6]]

 [[8 6 7 6 5 5 7 8]
  [5 8 6 8 8 6 7 8]
  [7 8 5 7 5 5 7 8]
  [5 8 8 8 6 5 8 6]
  [8 7 5 6 8 7 8 7]
  [6 6 6 6 7 6 6 6]
  [5 5 6 5 6 7 8 6]
  [7 6 8 5 6 8 6 5]]

 [[6 7 5 8 8 6 7 8]
  [8 7 7 6 7 5 5 6]
  [6 6 6 7 8 7 6 5]
  [7 7 7 5 5 5 6 8]
  [8 8 6 5 7 6 5 7]
  [6 6 7 5 6 8 6 7]
  [8 6 7 6 8 6 6 8]
  [7 5 6 6 8 5 6 6]]

 [[7 6 6 5 8 6 7 5]
  [5 6 6

In [0]:
# 2.Find the diagonal of product of two random 5x5 matrices
import numpy as np   
x = np.random.randint(1,5,(5,5))
y = np.random.randint(1,5,(5,5))
res = np.dot(x,y) 
# print resulted matrix 
print("product of two random 5x5 matrices is:",res)
dia=res.diagonal()
print("diagonal of product of two matrices is",dia)

product of two random 5x5 matrices is: [[22 34 20 24 24]
 [16 26 15 23 15]
 [31 44 36 49 39]
 [23 33 27 36 29]
 [16 27 20 26 19]]
diagonal of product of two matrices is [22 26 36 36 19]


In [0]:
# 3.Negate a boolean, or to change the the sign of the float inplace
import numpy as np
in_float_val=10.5
print("float number:",in_float_val)
out_float_val=np.negative(in_float_val)
print("negative of float value",out_float_val)


float number: 10.5
negative of float value -10.5


**Lab 6**

Given 100 random points in 2D space and find the top 10 closest points to the origin.

In [3]:
# Given 100 random points in 2D space and find the top 10 closest points to the origin.
import numpy as np 
z= np.random.rand(100,2)
np.flip(z[np.argsort(np.sqrt(np.sum(z*z,axis=1)))],axis=0)[0:10]

array([[0.9937818 , 0.97128911],
       [0.86485296, 0.98424517],
       [0.8516295 , 0.98071766],
       [0.90495955, 0.92635233],
       [0.75429381, 0.97554359],
       [0.73753578, 0.95680787],
       [0.70703503, 0.96656795],
       [0.67029862, 0.94989712],
       [0.91205534, 0.7146198 ],
       [0.93506582, 0.67368232]])

**Lab 7**

Find the value of pi using Monte Carlo simulation.

**Hint:-** 

Consider a unit circle which is enclosed in a square. randomly genrate uniformily distributed points inside the square. The fraction of points falling inside the circle is pi/4. 

In [0]:
# Lab 7.Find the value of pi using Monte Carlo simulation.
from pylab import plot,show,axis
from numpy import random,sqrt,pi

# scattering n points over the unit square
n = 1000000
p = random.rand(n,2)

# counting the points inside the unit circle
idx = sqrt(p[:,0]**2+p[:,1]**2) < 1

# estimation of pi
print ('%0.16f' % (sum(idx).astype('double')/n*4),'result')
print ('%0.16f' % pi,'real pi')

3.1438039999999998 result
3.1415926535897931 real pi


**Home Work**

1. wap the first two rows of a random 5x5
array
2. How to get the block-sum of a 16x16 matrix
(block size is 4x4)?
3. Sort an array by the nth column
4. Subtract the mean of each row of a matrix
from each element

In [0]:
# 1.wap the first two rows of a random 5x5 array
import numpy as np
x = np.random.randint(1,5,(5,5))
print(x)
y=x[:2]
print(y)


[[4 3 2 1 2]
 [3 1 4 3 4]
 [1 3 3 1 4]
 [4 3 3 2 4]
 [3 1 3 2 2]]
[[4 3 2 1 2]
 [3 1 4 3 4]]


In [0]:
# 2.How to get the block-sum of a 16x16 matrix (block size is 4x4)?
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [0]:
# 3.Sort an array by the nth column
import numpy as np
# Create a 2D Numpy array list of list
arr2D = np.array([[11, 12, 13, 22], [21, 7, 23, 14], [31, 10, 33, 7]])
print('2D Numpy Array')
print(arr2D)
columnIndex = 1
sortedArr = arr2D[arr2D[:,columnIndex].argsort()]
print('Sorted 2D Numpy Array')
print(sortedArr)

2D Numpy Array
[[11 12 13 22]
 [21  7 23 14]
 [31 10 33  7]]
Sorted 2D Numpy Array
[[21  7 23 14]
 [31 10 33  7]
 [11 12 13 22]]


In [0]:
# 4.Subtract the mean of each row of a matrix from each element
import pandas as pd
df.sub(df.mean(axis=1), axis=0)
df = pd.DataFrame({'a': [1.5, 2.5], 'b': [0.25, 2.75], 'c': [1.25, 0.75]})
print(df)
df.mean(axis=1)
df.sub(df.mean(axis=1), axis=0)


NameError: ignored