**Lab 1**
1. Use git init to create an empty repo
2. Add a file to local repo and push to github
3. Make additional changes to same file, again push to github
4. Add a collaborator to your repo
5. Ask you collaborator to make change to the file and push to repo
6. You try to make a diff change at the same place in the file and push to repo
7. Step6 will fail, Fix merge conflicts and push again
8. Verify all the commits in github
9. Revert code to previous version


**Lab 2**
1. Remove push access to master branch from your collabortator
2. Ask your collaborator to create a new branch
3. Push new code changes to that branch
4. Create a pull request from that branch to master branch
5. Approve and merge the pull request
6. Do a git pull and veirfy that you can see the new changes in master branch


https://github.com/pythonwithda/iitknov
https://github.com/drharshdev/harsh

**Lab 3**
1. Use python requests to post a comment on your commit
2. Use python requests to find top 10 commiters on django repo

In [10]:
import requests
import pprint
headers ={'Authorization': 'token 4cc3f05429d9a146158d245573ee0cd05b9dcdf0'}
json={'body': 'comment from api call', 'path':'index.html'}
r = requests.post('https://api.github.com/repos/drharshdev/harsh/commits/e04ec4c56e67b8f76ea257f1e2ebb610165163f7/comments',headers=headers,json=json)
#print(r.text)
pprint.pprint(r.json())
#4cc3f05429d9a146158d245573ee0cd05b9dcdf0 

{'author_association': 'OWNER',
 'body': 'comment from api call',
 'commit_id': 'e04ec4c56e67b8f76ea257f1e2ebb610165163f7',
 'created_at': '2019-11-10T09:29:17Z',
 'html_url': 'https://github.com/drharshdev/harsh/commit/e04ec4c56e67b8f76ea257f1e2ebb610165163f7#commitcomment-35883049',
 'id': 35883049,
 'line': None,
 'node_id': 'MDEzOkNvbW1pdENvbW1lbnQzNTg4MzA0OQ==',
 'path': 'index.html',
 'position': None,
 'updated_at': '2019-11-10T09:29:17Z',
 'url': 'https://api.github.com/repos/drharshdev/harsh/comments/35883049',
 'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/46295689?v=4',
          'events_url': 'https://api.github.com/users/drharshdev/events{/privacy}',
          'followers_url': 'https://api.github.com/users/drharshdev/followers',
          'following_url': 'https://api.github.com/users/drharshdev/following{/other_user}',
          'gists_url': 'https://api.github.com/users/drharshdev/gists{/gist_id}',
          'gravatar_id': '',
          'html_url': 'ht

**Lab 4**
1. Create a 8x8x8 array with random values
2. From the matrix in (1) Negate all elements
whose values are between 3 to 8
3. Multiply a 8x3 matrix by 3x2 matrix and
prints the columns as 1 D array

In [27]:
import numpy as np
a=np.random.randint(1,10,(8,8,8))
print(a)
mask=(a>3)&(a<8)
a[mask]=-1*a[mask]
print(a)

[[[4 7 1 4 6 3 4 1]
  [4 4 7 5 8 6 8 1]
  [1 8 7 4 3 4 5 7]
  [5 8 4 6 6 7 9 5]
  [8 1 2 5 8 5 1 9]
  [9 4 2 8 9 8 8 3]
  [2 2 3 7 2 1 3 1]
  [9 5 1 4 4 1 7 9]]

 [[4 9 6 5 9 2 8 4]
  [5 9 8 4 3 5 5 7]
  [5 9 3 7 5 6 9 9]
  [9 4 5 3 5 3 2 5]
  [8 7 6 4 2 7 2 4]
  [3 1 6 1 7 4 2 6]
  [8 5 6 7 7 6 2 6]
  [1 1 9 4 5 8 2 1]]

 [[2 2 6 1 2 4 1 8]
  [8 7 9 3 8 4 8 3]
  [3 9 4 9 2 1 2 7]
  [6 2 8 7 1 8 7 2]
  [6 9 6 5 2 1 3 3]
  [4 8 3 9 6 7 6 7]
  [7 1 6 7 2 2 3 1]
  [6 9 7 2 1 5 9 6]]

 [[9 1 4 2 3 6 3 7]
  [6 1 8 3 5 9 9 5]
  [9 2 5 1 6 1 4 2]
  [2 2 1 7 2 4 8 6]
  [3 8 2 3 3 4 5 4]
  [7 1 1 7 3 5 8 5]
  [9 2 6 7 6 4 8 3]
  [1 7 3 8 7 4 1 6]]

 [[8 9 8 8 1 9 6 2]
  [2 3 3 6 3 4 1 8]
  [9 1 3 6 2 9 6 9]
  [4 7 1 7 2 5 7 4]
  [6 9 6 7 4 2 4 2]
  [4 2 8 1 6 6 4 3]
  [6 2 8 9 6 2 3 4]
  [1 1 1 3 4 6 4 4]]

 [[2 9 7 4 6 3 5 5]
  [8 3 4 6 4 2 9 9]
  [5 2 6 6 2 7 8 5]
  [4 9 3 8 5 4 7 5]
  [8 4 8 6 4 2 8 5]
  [7 7 5 6 1 3 4 9]
  [2 4 3 5 9 8 6 9]
  [8 8 9 4 3 4 3 9]]

 [[9 9 3 4 1 8 9 7]
  [8 5 5

In [30]:
a=np.random.randint(1,10,(8,3))
b=np.random.randint(1,10,(3,2))
c=np.dot(a,b)
print(c)
d=c.reshape(1,16)
print(d)
#Multiply a 8x3 matrix by 3x2 matrix and prints the columns as 1 D array

[[85 43]
 [56 42]
 [42 25]
 [70 44]
 [80 56]
 [99 73]
 [70 44]
 [88 54]]
[[85 43 56 42 42 25 70 44 80 56 99 73 70 44 88 54]]


**Lab 5**

1. Create a 8x8x8 matrix with random values ranging from 5 to 9
2. Find the diagonal of product of two random 5x5 matrices
3. Negate a boolean, or to change the the sign of the float inplace

In [45]:
a=np.random.randint(5,9,(8,8,8))
a

array([[[5, 8, 6, 5, 8, 8, 8, 7],
        [6, 5, 6, 8, 8, 8, 6, 5],
        [6, 6, 6, 6, 5, 8, 6, 8],
        [7, 7, 8, 7, 6, 6, 8, 7],
        [8, 6, 8, 6, 7, 8, 8, 7],
        [8, 6, 7, 8, 5, 8, 6, 6],
        [7, 6, 5, 6, 6, 7, 8, 5],
        [6, 7, 8, 8, 5, 8, 8, 7]],

       [[6, 8, 8, 8, 6, 5, 7, 7],
        [5, 7, 6, 6, 6, 6, 8, 7],
        [8, 5, 6, 8, 5, 8, 5, 5],
        [7, 7, 7, 6, 8, 7, 5, 8],
        [7, 5, 6, 8, 5, 5, 6, 8],
        [7, 8, 7, 7, 5, 5, 6, 7],
        [8, 6, 8, 5, 6, 5, 8, 6],
        [7, 7, 6, 5, 6, 6, 7, 6]],

       [[6, 7, 8, 8, 5, 8, 5, 5],
        [8, 7, 7, 6, 7, 5, 8, 5],
        [7, 5, 7, 7, 6, 7, 7, 5],
        [8, 5, 7, 7, 5, 7, 8, 6],
        [7, 7, 8, 6, 7, 7, 6, 6],
        [6, 8, 8, 7, 5, 6, 5, 6],
        [6, 5, 7, 5, 8, 5, 5, 5],
        [7, 8, 6, 5, 8, 6, 7, 6]],

       [[5, 6, 6, 8, 6, 5, 6, 7],
        [8, 8, 7, 5, 6, 6, 8, 8],
        [5, 5, 6, 6, 8, 7, 7, 5],
        [8, 6, 8, 7, 5, 7, 5, 7],
        [7, 5, 8, 5, 5, 6, 8, 6],
        

In [56]:
a=np.random.randn(5,5)
b=np.random.randn(5,5)
matrix=np.dot(a,b)
print(matrix)
print(matrix.diagonal().tolist())
# Find the diagonal of product of two random 5x5 matrices

[[ 2.503807    3.55826274 -0.47418411 -0.82855637 -3.84867022]
 [ 0.55500471  0.62669883  0.32750808  1.35484868 -1.25319518]
 [-0.56823132  1.20197233 -2.90730653  2.61794707 -0.39889758]
 [ 1.23868966  2.5471241  -0.83749565  0.08815523 -2.74447424]
 [-1.856336   -2.47830472  2.57671686 -0.68197931  3.59857473]]
[2.5038070025364276, 0.6266988289410795, -2.907306526020603, 0.08815522921794437, 3.598574731928918]


In [65]:
# Negate a boolean, or 
Z = np.random.randint(0,2,100)
print (Z)
print(np.logical_not(Z, out=Z))
#to change the the sign of the float inplace
Z = np.random.uniform(-1.0,1.0,10)
print (Z)
print(np.negative(Z, out=Z))


[1 1 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 1 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1 1 0 1
 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 1 1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 1 1
 1 1 1 0 0 1 0 0 0 1 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 0]
[0 0 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1 1 0 0 0 0 1 0
 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 0 1 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0
 0 0 0 1 1 0 1 1 1 0 0 1 1 0 1 0 1 0 1 1 0 0 0 0 1 1]
[ 0.42481972 -0.90385639 -0.36122842  0.74464839  0.57193533  0.98204428
 -0.68286608  0.51769065  0.03961442  0.99971991]
[-0.42481972  0.90385639  0.36122842 -0.74464839 -0.57193533 -0.98204428
  0.68286608 -0.51769065 -0.03961442 -0.99971991]


**Lab 6**

Given 100 random points in 2D space and find the top 10 closest points to the origin.

In [37]:
z=np.random.randn(100,2)
np.flip(z[np.argsort(np.sort(np.sum(z*z,axis=1)))],axis=0)[0:10]

array([[ 0.15392434,  0.16793366],
       [-1.85154683,  0.4101626 ],
       [-0.73360752, -0.37900753],
       [-0.31896688,  0.00648993],
       [-0.71449872, -0.54378224],
       [ 1.22731525, -1.34939152],
       [ 0.01373011,  2.48406   ],
       [ 1.60888277, -0.84295975],
       [ 0.1355704 ,  2.25047996],
       [ 0.69269757, -2.10035128]])

**Lab 7**

Find the value of pi using Monte Carlo simulation.

**Hint:-** 

Consider a unit circle which is enclosed in a square. randomly genrate uniformily distributed points inside the square. The fraction of points falling inside the circle is pi/4. 

In [71]:
from numpy import random,sqrt,pi
n = 10000000
p = random.rand(n,2)
# counting the points inside the unit circle
idx = sqrt(p[:,0]**2+p[:,1]**2) < 1
# estimation of pi
print((sum(idx)/n*4),'program result')
print(pi,'correct pi value')

3.1420124 program result
3.141592653589793 correct pi value


In [1]:
print("harsh")

harsh


**Home Work**

1. wap the first two rows of a random 5x5
array
2. How to get the block-sum of a 16x16 matrix
(block size is 4x4)?
3. Sort an array by the nth column
4. Subtract the mean of each row of a matrix
from each element

In [69]:
z=np.random.randn(5,5)
print(z)
y=z[:2,:]
print(y)

[[-0.28956278 -1.87058373  1.02984605 -0.10759459 -0.82896332]
 [ 0.31284969  0.88320939  1.16980926 -0.55619537  1.44582422]
 [-0.03441379 -1.6618732   0.97880585  1.32703105  1.61498249]
 [ 1.59973627 -0.33085487 -0.05309039 -2.61753079  1.11691162]
 [-1.35598991 -0.16701558  0.83482777  1.23521133 -0.33566942]]
[[-0.28956278 -1.87058373  1.02984605 -0.10759459 -0.82896332]
 [ 0.31284969  0.88320939  1.16980926 -0.55619537  1.44582422]]


In [68]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
print ('input array is: ')
print (Z)
print ('block sum is: ')
print (S)

input array is: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum is: 
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [67]:
# Sort an array by the nth column
Z = np.random.randint(0,10,(4,4))
print(Z)
# sorting third column
print(Z[Z[:,2].argsort()])

[[3 9 4 1]
 [9 1 6 1]
 [4 0 5 8]
 [4 3 2 1]]
[[4 3 2 1]
 [3 9 4 1]
 [4 0 5 8]
 [9 1 6 1]]


In [66]:
# Subtract the mean of each row of a matrix from each element
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.29860202 -0.42581683  0.29125435  0.17312101 -0.10408688  0.16392164
   0.18788611 -0.00903499 -0.03890004  0.06025765]
 [-0.22641035  0.35633687  0.02857022 -0.03164035 -0.04491531 -0.02870857
   0.05343822 -0.10438384 -0.25297096  0.25068407]
 [-0.25169722  0.13041782 -0.31420992  0.28594844 -0.29468018  0.60993219
  -0.10469006 -0.29772333  0.1880576   0.04864465]
 [-0.38202337  0.4874029   0.43477271 -0.2357674   0.51423483  0.10902146
   0.27557222 -0.44462624 -0.38661751 -0.37196959]
 [ 0.04763264 -0.55444122  0.12878252 -0.46085065  0.19570189 -0.01669671
   0.05023839  0.07385402  0.19099575  0.34478339]]
[[-0.29860202 -0.42581683  0.29125435  0.17312101 -0.10408688  0.16392164
   0.18788611 -0.00903499 -0.03890004  0.06025765]
 [-0.22641035  0.35633687  0.02857022 -0.03164035 -0.04491531 -0.02870857
   0.05343822 -0.10438384 -0.25297096  0.25068407]
 [-0.25169722  0.13041782 -0.31420992  0.28594844 -0.29468018  0.60993219
  -0.10469006 -0.29772333  0.1880576   0.04864465]

In [11]:
#GET /repos/:owner/:repo/stats/contributors
import requests
import pprint
headers ={'Authorization': 'token 4cc3f05429d9a146158d245573ee0cd05b9dcdf0'}
r = requests.get('https://api.github.com/repos/django/django/stats/contributors',headers=headers)
#print(r.text)
l=r.json()
#print(l)
print(l[0]['total'])

12


In [12]:
#value_counts()
import pandas as pd
df=pd.read_csv()

NameError: ignored