**Lab 1**
1. Use git init to create an empty repo
2. Add a file to local repo and push to github
3. Make additional changes to same file, again push to github
4. Add a collaborator to your repo
5. Ask you collaborator to make change to the file and push to repo
6. You try to make a diff change at the same place in the file and push to repo
7. Step6 will fail, Fix merge conflicts and push again
8. Verify all the commits in github
9. Revert code to previous version


In [0]:
import requests
r=requests.get("https://www.iitk.ac.in/")
print(r.headers)

{'Date': 'Sun, 10 Nov 2019 09:08:26 GMT', 'Server': 'Apache', 'Set-Cookie': 'd8fdb0c7bbb290989fe5b71584d38355=1b62o93ksp044eskqenaof9db0; path=/', 'P3P': 'CP="NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM"', 'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Connection': 'close', 'Transfer-Encoding': 'chunked', 'Content-Type': 'text/html; charset=utf-8'}


**Lab 2**
1. Remove push access to master branch from your collabortator
2. Ask your collaborator to create a new branch
3. Push new code changes to that branch
4. Create a pull request from that branch to master branch
5. Approve and merge the pull request
6. Do a git pull and veirfy that you can see the new changes in master branch


**Lab 3**
1. Use python requests to post a comment on your commit
2. Use python requests to find top 10 commiters on django repo

In [0]:
import requests
import pprint
headers={'Authorization':'token '}
json={'body':'comment from api cell'.'path':'index.html'}
r=requests.post{https://api.github.com/repos/mishranayanshi//commit/ef811dec779777323e10760cff2d9e3b022a1a92/comments'headers=headers,json=json)
pprint.pprint(r.json())

In [0]:
#1.
import numpy as np  
arr = np.random.randint(1,10,(8,8,8))
print(arr)



**Lab 4**
1. Create a 8x8x8 array with random values
2. From the matrix in (1) Negate all elements
whose values are between 3 to 8
3. Multiply a 8x3 matrix by 3x2 matrix and
prints the columns as 1 D array

In [0]:
#Create a 8x8x8 array with random values
import numpy as np
x=np.random.randint(1,10,(8,8,8))
print(x)


In [0]:
#From the matrix in (1) Negate all elements whose values are between 3 to 8
import numpy as np
x=np.random.randint(1,10,(8,8,8))
mask=(x>3)&(x<8)
x[mask]=-1*x[mask]
print(x)


In [0]:
#3.Multipication
import numpy as np
x = np.random.randint(1,10,(8,3))
y = np.random.randint(1,10,(3,2))
res = np.dot(x,y)
print(res[:,0])

[89 45 48 46 42 53 45 23]


**Lab 5**

1. Create a 8x8x8 matrix with random values ranging from 5 to 9
2. Find the diagonal of product of two random 5x5 matrices
3. Negate a boolean, or to change the the sign of the float inplace

In [0]:
#1.Create a 8x8x8 matrix with random values ranging from 5 to 9
import numpy as np
x=np.random.randint(5,9,(8,8,8))
print(x)

In [6]:
# 2.Find the diagonal of product of two random 5x5 matrices
import numpy as np
x=np.random.randint(1,5,(5,5))
y=np.random.randint(1,5,(5,5))
res=np.dot(x,y)
print(res)
dia=res.diagonal()
print("Diagnonal of result matrix",dia)

[[44 48 37 45 49]
 [30 36 31 32 32]
 [24 26 16 22 21]
 [25 24 21 25 33]
 [26 30 23 30 31]]
Diagnonal of result matrix [44 36 16 25 31]


In [11]:
# 3.Negate a boolean, or to change the the sign of the float inplace
import numpy as np
in_float_val=10.5
print("float number:",in_float_val)
out_float_val=np.negative(in_float_val)
print("negative value of float value",out_float_val)

float number: 10.5
negative value of float value -10.5


**Lab 6**

Given 100 random points in 2D space and find the top 10 closest points to the origin.

In [12]:
import numpy as np
z=np.random.randn(100,2)
z[np.argsort(np.sqrt(np.sum(z*z,axis=1)))]
#coordinates = np.random.randn(100,2)
print("100 random point in 2D space",z)
dist=np.sqrt(coordinates[:,0]**2+coordinates[:,1]**2)
top_10=np.argsort(dist)[:10]
print("Top 10 closest point to the origin",coordinates[top_10])




100 random point in 2D space [[ 1.76656155 -1.13675309]
 [ 0.21859448  0.64083783]
 [ 1.15538538 -0.23588819]
 [ 0.46856026  0.05277423]
 [-0.90772872 -0.83814744]
 [ 1.07688406 -1.02118846]
 [ 0.80989178 -0.57025932]
 [-0.3201165  -0.94844344]
 [-0.27523579  0.79224532]
 [ 1.29516276 -0.78222376]
 [ 0.07840192 -0.22949759]
 [ 1.70550377  0.33861101]
 [ 2.25249694 -1.02384181]
 [ 0.2574941  -1.1836289 ]
 [ 1.55233731 -0.25034574]
 [ 0.16926844  0.51847392]
 [-0.30174869  1.14195025]
 [ 0.72493159  0.61873891]
 [-0.03785231 -0.20824561]
 [ 0.01161702 -2.75150326]
 [-1.24956425 -0.7173795 ]
 [ 0.99499455 -0.81697125]
 [-1.42309139  0.85390016]
 [ 1.25743729 -1.08664353]
 [ 0.13968625 -0.49340252]
 [ 0.82411878  0.96751177]
 [-2.08007806 -0.48511461]
 [-0.37104465 -1.78669745]
 [-1.02048944  1.6795652 ]
 [ 0.45473172 -1.16742158]
 [ 1.18959165 -1.44939539]
 [-0.4610103  -0.26917092]
 [-2.37555856  0.10776085]
 [ 0.69525781 -2.62893191]
 [-0.36000161  1.36994255]
 [ 1.22692811 -0.2007    ]

NameError: ignored

**Lab 7**

Find the value of pi using Monte Carlo simulation.

**Hint:-** 

Consider a unit circle which is enclosed in a square. randomly genrate uniformily distributed points inside the square. The fraction of points falling inside the circle is pi/4. 

In [0]:
from pylab import plot,show,axis
from numpy import random,sqrt,pi

# scattering n points over the unit square
n = 1000000
p = random.rand(n,2)

# counting the points inside the unit circle
idx = sqrt(p[:,0]**2+p[:,1]**2) < 1

# estimation of pi
print('%0.16f' % (sum(idx).astype('double')/n*4),'result')
print( '%0.16f' % pi,'real pi')

3.1392039999999999 result
3.1415926535897931 real pi


**Home Work**

1. wap the first two rows of a random 5x5
array
2. How to get the block-sum of a 16x16 matrix
(block size is 4x4)?
3. Sort an array by the nth column
4. Subtract the mean of each row of a matrix
from each element

In [0]:
import requests
r=requests.get('https://api.github.com/user/repos')
print(r.status_code)

401


In [0]:
import requests
import pprint
headers={'Authorization':'token 3c5ee7fc3ed16d89ede255647fbbd0e0c50bff13'}
r=requests.get('https://api.github.com/user/repos',headers=headers)
pprint.pprint(r.json())