**Lab 1**
1. Use git init to create an empty repo
2. Add a file to local repo and push to github
3. Make additional changes to same file, again push to github
4. Add a collaborator to your repo
5. Ask you collaborator to make change to the file and push to repo
6. You try to make a diff change at the same place in the file and push to repo
7. Step6 will fail, Fix merge conflicts and push again
8. Verify all the commits in github
9. Revert code to previous version


**Lab 2**
1. Remove push access to master branch from your collabortator
2. Ask your collaborator to create a new branch
3. Push new code changes to that branch
4. Create a pull request from that branch to master branch
5. Approve and merge the pull request
6. Do a git pull and veirfy that you can see the new changes in master branch


**Lab 3**
1. Use python requests to post a comment on your commit
2. Use python requests to find top 10 commiters on django repo

In [0]:
import requests
import pprint
headers = {'Authorization': 'token'}
#response = requests.get('https://api.github.com/user/repos', headers=headers)
json = {'body': 'comment from api call', 'path':'index.html'}
response = requests.post('https://api.github.com/user/repos/nimitiitk/python/commits/0c0dc4b7ba892aabad58084318d2cd1d480824f5', headers=headers,json=json)
pprint.pprint(response.json())

{'documentation_url': 'https://developer.github.com/v3', 'message': 'Not Found'}


In [0]:
import requests
response = requests.get(" https://www.django-rest-framework.org")
print(response.json())

JSONDecodeError: ignored

**Lab 4**
1. Create a 8x8x8 array with random values
2. From the matrix in (1) Negate all elements
whose values are between 3 to 8
3. Multiply a 8x3 matrix by 3x2 matrix and
prints the columns as 1 D array

In [0]:
import numpy as np
grid = np.random.randn(8,8,8)
print(grid)
print(grid.ndim)

[[[-1.36004714 -0.16040054 -0.41518882 -1.16072376  1.64488273
    1.0084907  -1.63523439 -0.81167696]
  [ 0.69342613  0.65935348 -0.66223756 -0.67392288  0.16368506
   -0.08669986  0.84557202  0.42631362]
  [ 1.20264996  0.60288245 -0.70385964  1.00838985  0.28605227
    0.70872535  1.68584285  0.45961118]
  [-0.00998611 -0.54799587  0.52652208 -0.94277447 -2.31141557
   -1.22969675  0.79450591  1.26137426]
  [ 0.49424783  1.46152519 -0.45376799 -1.0124029   1.39216796
   -0.86490476 -0.13515601 -1.10440699]
  [ 0.9892394   0.97958212 -0.16046458  1.2904285  -0.30399553
    1.27407478 -0.27907457 -1.474716  ]
  [ 1.31319464  0.10840939 -1.38852938  1.96053501 -1.37521988
   -0.55062515  1.09396694 -0.15431135]
  [ 0.32250717  0.49495911  0.1128714   0.37898402  0.69778335
    1.6752385  -0.39884836 -0.50264084]]

 [[-0.30427022  0.91396237 -0.05366863  1.30170299  1.51009436
    1.33529683 -0.76870642  0.7660807 ]
  [ 0.38854322 -0.62107006  2.14543252  0.07524584  1.95208957
   -1.59

**Lab 5**

1. Create a 8x8x8 matrix with random values ranging from 5 to 9
2. Find the diagonal of product of two random 5x5 matrices
3. Negate a boolean, or to change the the sign of the float inplace

In [0]:
grid = np.random.randint(5,9, (8,8,8))
print(grid)

[[[7 6 7 7 8 5 5 8]
  [7 6 8 6 8 8 7 8]
  [6 5 8 7 6 8 5 6]
  [7 5 8 8 8 6 6 5]
  [7 6 7 5 8 6 6 6]
  [6 6 5 5 7 6 6 8]
  [6 7 6 7 8 5 6 6]
  [7 6 7 6 6 8 6 6]]

 [[5 7 7 5 7 6 5 7]
  [6 8 8 5 6 7 5 8]
  [6 6 8 8 5 7 8 6]
  [8 6 6 5 5 7 8 8]
  [5 7 6 5 5 5 6 5]
  [5 6 6 5 5 5 8 8]
  [5 7 7 7 7 6 8 8]
  [6 7 7 7 5 7 5 5]]

 [[8 6 7 8 8 7 6 7]
  [6 8 8 7 5 7 7 6]
  [7 6 7 6 6 6 8 7]
  [7 8 5 5 6 5 6 7]
  [6 6 6 5 6 6 8 6]
  [6 8 6 5 7 8 7 5]
  [7 6 6 5 6 7 5 8]
  [5 8 8 7 8 7 6 5]]

 [[7 6 7 7 7 6 6 7]
  [7 6 7 7 5 7 5 8]
  [6 7 6 5 5 6 5 6]
  [5 5 8 5 7 7 7 7]
  [5 6 8 8 8 5 5 6]
  [7 6 5 6 7 7 6 5]
  [6 6 8 6 5 5 5 6]
  [8 7 7 5 7 5 7 6]]

 [[5 7 5 6 5 5 7 7]
  [6 7 7 8 6 5 7 5]
  [8 8 5 6 7 7 5 7]
  [5 6 8 5 7 6 5 7]
  [6 6 6 8 8 6 7 6]
  [6 8 8 5 7 5 5 6]
  [7 6 8 7 8 6 8 7]
  [6 5 6 8 5 6 5 7]]

 [[5 6 5 5 5 6 5 6]
  [5 8 7 5 5 5 5 6]
  [8 5 7 5 5 8 7 8]
  [8 5 6 7 5 8 7 5]
  [8 5 7 6 6 7 6 5]
  [5 7 6 7 5 8 7 6]
  [8 7 7 6 5 5 7 6]
  [6 5 6 5 5 7 5 5]]

 [[7 8 7 6 6 5 5 8]
  [7 8 6

In [0]:
grid = np.random.randint(10,(5,5))
grid_1 = np.random.rand(10, (5,5))
print(grid)

ValueError: ignored

**Lab 6**

Given 100 random points in 2D space and find the top 10 closest points to the origin.

**Lab 7**

Find the value of pi using Monte Carlo simulation.

**Hint:-** 

Consider a unit circle which is enclosed in a square. randomly genrate uniformily distributed points inside the square. The fraction of points falling inside the circle is pi/4. 

In [31]:
import numpy as np

var = 1000000
val = np.random.rand(n,2)
idx = np.sqrt(val[:,0]**2+val[:,1]**2) < 1
print ('%0.16f' % (sum(idx).astype('double')/var*4),'result')
print ('%0.16f' % np.pi,'real pi')

3.1436039999999998 result
3.1415926535897931 real pi


**Home Work**

1. wap the first two rows of a random 5x5
array
2. How to get the block-sum of a 16x16 matrix
(block size is 4x4)?
3. Sort an array by the nth column
4. Subtract the mean of each row of a matrix
from each element

In [32]:
import numpy as np
arr = np.arange(25).reshape(5, 5) 
print(arr)
arr[[0, 1],:] = arr[[1, 0],:]
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [33]:
import numpy as np
arr = np.random.randint(1,100,(16,16))
print(arr)
arr2 = np.sum(arr)
print(arr2)

[[89  8 44 41 16 19  9 76 36 72 58 98 45  1 34 91]
 [68 39  5 83  2 31 53 36 45 64 31 76 42 11 66 83]
 [74 93 56 20 21 16 83 86 55 91 29 87 68 82 56 61]
 [83 59 31 75 11 49 11 30 66 69 59 66 27 57 68 37]
 [82 16 51 15 44  3 15 52  8 47 36 84 36 74 50 30]
 [13 58 14 74 11 79 83 75 71 77 28 29 61 39 24  7]
 [81  8 27 71 81 70 74 30 63 50 69 37 14 98  1 39]
 [59 76 80 13 62 89 13 69 31  1 95 71 75 85 95  5]
 [63 82 62 62  6 53 49  1  3 19 49 66  5 15 74 23]
 [93 98 55 92 38 43 31  9 96 64 21 94 94  4 71 53]
 [88 55 98 24 83 55 56 14 17 36 99 77 43 49 36 19]
 [89 89 38 85 95 91 73 24  8 19 93  1  7 40 71 68]
 [80 30 95 96 99  2 10 12 92 30  1 67 30 50 85 99]
 [75 81 25 94  2  7  6 35 47  6 21 72 66 89 34 75]
 [78 87 42 10 63 95 35 64 83 67 97 39 51 70 91 48]
 [72 90 51 60 40 66 52 83 36 13 19 74 84  6 45 71]]
13189


In [34]:
arr3 = np.sort(arr)
print(arr3)

[[ 1  8  9 16 19 34 36 41 44 45 58 72 76 89 91 98]
 [ 2  5 11 31 31 36 39 42 45 53 64 66 68 76 83 83]
 [16 20 21 29 55 56 56 61 68 74 82 83 86 87 91 93]
 [11 11 27 30 31 37 49 57 59 59 66 66 68 69 75 83]
 [ 3  8 15 15 16 30 36 36 44 47 50 51 52 74 82 84]
 [ 7 11 13 14 24 28 29 39 58 61 71 74 75 77 79 83]
 [ 1  8 14 27 30 37 39 50 63 69 70 71 74 81 81 98]
 [ 1  5 13 13 31 59 62 69 71 75 76 80 85 89 95 95]
 [ 1  3  5  6 15 19 23 49 49 53 62 62 63 66 74 82]
 [ 4  9 21 31 38 43 53 55 64 71 92 93 94 94 96 98]
 [14 17 19 24 36 36 43 49 55 55 56 77 83 88 98 99]
 [ 1  7  8 19 24 38 40 68 71 73 85 89 89 91 93 95]
 [ 1  2 10 12 30 30 30 50 67 80 85 92 95 96 99 99]
 [ 2  6  6  7 21 25 34 35 47 66 72 75 75 81 89 94]
 [10 35 39 42 48 51 63 64 67 70 78 83 87 91 95 97]
 [ 6 13 19 36 40 45 51 52 60 66 71 72 74 83 84 90]]


In [35]:
arr5 = np.mean(arr, axis = 0)
print(arr5)

[74.1875 60.5625 48.375  57.1875 42.125  48.     40.8125 43.5    47.3125
 45.3125 50.3125 64.875  46.75   48.125  56.3125 50.5625]
