**Lab 1**
1. Use git init to create an empty repo
2. Add a file to local repo and push to github
3. Make additional changes to same file, again push to github
4. Add a collaborator to your repo
5. Ask you collaborator to make change to the file and push to repo
6. You try to make a diff change at the same place in the file and push to repo
7. Step6 will fail, Fix merge conflicts and push again
8. Verify all the commits in github
9. Revert code to previous version


In [0]:
import requests
r = requests.get('https://www.iitk.ac.in/')
print(r.headers)

{'Date': 'Sun, 10 Nov 2019 09:11:22 GMT', 'Server': 'Apache', 'Set-Cookie': 'd8fdb0c7bbb290989fe5b71584d38355=056l0agerirui80odo1196iqb2; path=/', 'P3P': 'CP="NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM"', 'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Connection': 'close', 'Transfer-Encoding': 'chunked', 'Content-Type': 'text/html; charset=utf-8'}


In [0]:
import requests 
import pprint
headers={'Authorization':'token 847dae6b3edfe50efa1d70f9ba6b2e2ce9de2699'}
r = requests.get('https://api.github.com/user/repos', headers = headers)
pprint.pprint(r.json())

[{'archive_url': 'https://api.github.com/repos/nimitiitk/python/{archive_format}{/ref}',
  'archived': False,
  'assignees_url': 'https://api.github.com/repos/nimitiitk/python/assignees{/user}',
  'blobs_url': 'https://api.github.com/repos/nimitiitk/python/git/blobs{/sha}',
  'branches_url': 'https://api.github.com/repos/nimitiitk/python/branches{/branch}',
  'clone_url': 'https://github.com/nimitiitk/python.git',
  'collaborators_url': 'https://api.github.com/repos/nimitiitk/python/collaborators{/collaborator}',
  'comments_url': 'https://api.github.com/repos/nimitiitk/python/comments{/number}',
  'commits_url': 'https://api.github.com/repos/nimitiitk/python/commits{/sha}',
  'compare_url': 'https://api.github.com/repos/nimitiitk/python/compare/{base}...{head}',
  'contents_url': 'https://api.github.com/repos/nimitiitk/python/contents/{+path}',
  'contributors_url': 'https://api.github.com/repos/nimitiitk/python/contributors',
  'created_at': '2019-11-09T12:09:30Z',
  'default_branch'

**Lab 2**
1. Remove push access to master branch from your collabortator
2. Ask your collaborator to create a new branch
3. Push new code changes to that branch
4. Create a pull request from that branch to master branch
5. Approve and merge the pull request
6. Do a git pull and veirfy that you can see the new changes in master branch


**Lab 3**
1. Use python requests to post a comment on your commit
2. Use python requests to find top 10 commiters on django repo

In [0]:
import requests 
import pprint
headers={'Authorization':'token 847dae6b3edfe50efa1d70f9ba6b2e2ce9de2699'}
json={'body': 'comment from api call','path':'index.html'}
r = requests.post('https://api.github.com/repos/rocksns25', headers = headers,json=json)
pprint.pprint(r.json())

{'documentation_url': 'https://developer.github.com/v3', 'message': 'Not Found'}


**Lab 4**
1. Create a 8x8x8 array with random values
2. From the matrix in (1) Negate all elements
whose values are between 3 to 8
3. Multiply a 8x3 matrix by 3x2 matrix and
prints the columns as 1 D array

**Lab 5**

1. Create a 8x8x8 matrix with random values ranging from 5 to 9
2. Find the diagonal of product of two random 5x5 matrices
3. Negate a boolean, or to change the the sign of the float inplace

In [0]:
x=np.random.randint(1,10,(8,3))
b=np.random.randint(1,10,(3,2))
res = np.dot(x,b)
print(res)


[[121  59]
 [ 49  46]
 [ 89  45]
 [ 36  25]
 [ 29  28]
 [ 67  35]
 [104  59]
 [ 44  26]]


**Lab 6**

Given 100 random points in 2D space and find the top 10 closest points to the origin.

In [0]:
z=np.random.randn(100,2)
z.shape

(100, 2)

In [0]:
z=np.random.randn(100,2)
z.shape
z[np.argsort(np.sqrt(np.sum(z*z,axis=1)))]

array([[-0.00427047,  0.03440159],
       [ 0.03352602, -0.07421618],
       [ 0.06030394,  0.06068605],
       [ 0.11694488,  0.07502643],
       [ 0.20079669, -0.21815619],
       [ 0.30106851, -0.01659066],
       [ 0.1833769 ,  0.27248705],
       [-0.23533425,  0.26408016],
       [ 0.09700881,  0.39108831],
       [-0.38610024,  0.18744054],
       [ 0.41755341, -0.12062813],
       [ 0.25060941,  0.43720231],
       [-0.12730783, -0.48959931],
       [-0.246314  , -0.45656332],
       [ 0.5279208 , -0.11349036],
       [ 0.252353  , -0.48282304],
       [ 0.09094691,  0.54911439],
       [ 0.48280942,  0.31739708],
       [-0.5187798 ,  0.30597402],
       [-0.60022797, -0.19285483],
       [-0.36860315, -0.52212454],
       [-0.35496954, -0.61380657],
       [-0.37603379,  0.61590529],
       [ 0.02585131, -0.77451952],
       [ 0.04618402,  0.79645215],
       [ 0.17263446,  0.77923469],
       [ 0.68954381, -0.43926969],
       [-0.02981032,  0.82453949],
       [-0.83050739,

**Lab 7**

Find the value of pi using Monte Carlo simulation.

**Hint:-** 

Consider a unit circle which is enclosed in a square. randomly genrate uniformily distributed points inside the square. The fraction of points falling inside the circle is pi/4. 

**Home Work**

1. wap the first two rows of a random 5x5
array
2. How to get the block-sum of a 16x16 matrix
(block size is 4x4)?
3. Sort an array by the nth column
4. Subtract the mean of each row of a matrix
from each element

In [0]:
from numpy import random, sqrt, pi
n=1000000
p=random.rand(n,2)
idx = sqrt (p[:,0]**2+p[:,1]**2)<1

print(sum(idx)/n*4, 'result')
print(pi,'real pi')

3.144468 result
3.141592653589793 real pi


In [0]:
import numpy as np
z=np.random.randn(100,2)
a1=z[np.argsort(np.sqrt(np.sum(z*z,axis=1)))]
np.savez('tmp.npz',xyz=z,abc=a1)
a=np.load('tmp.npz')
a['abc']

array([[-0.01477534,  0.16777485],
       [ 0.06902583,  0.17546153],
       [ 0.184345  , -0.15063667],
       [ 0.10803953, -0.31729842],
       [ 0.35059865, -0.14664939],
       [ 0.4014755 , -0.17495271],
       [ 0.31573289, -0.37437348],
       [-0.15066449, -0.473717  ],
       [ 0.46384298, -0.24612103],
       [ 0.48457909, -0.22194715],
       [-0.05199184,  0.5555379 ],
       [-0.29892024,  0.49383819],
       [-0.48431763, -0.31579803],
       [ 0.6080884 , -0.02185343],
       [-0.60279134, -0.13509573],
       [ 0.59468704,  0.18162371],
       [ 0.57463753,  0.25846156],
       [ 0.57365118, -0.26643656],
       [-0.660293  , -0.22241783],
       [ 0.62350678,  0.35716357],
       [-0.74672433, -0.09714205],
       [ 0.81278943, -0.15065052],
       [ 0.56191272,  0.6089917 ],
       [-0.73085407,  0.40408218],
       [ 0.83901563, -0.12955688],
       [-0.13426026,  0.84196075],
       [-0.65310176, -0.58320519],
       [ 0.60991467, -0.63597919],
       [ 0.43304722,

In [0]:
Z = np.ones((16,16))
 
print(Z)
print("====")
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
====
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [0]:
z=np.random.rand(5,5)
print(z)
rows = z[:2, :]
 
print('Rows from Index 1 to 2 :')
print(rows)


[[0.44730497 0.57359309 0.87743353 0.81901719 0.65695698]
 [0.96623368 0.81135656 0.34887505 0.84605755 0.56605387]
 [0.67088296 0.85446992 0.43541619 0.85392703 0.27197757]
 [0.96519105 0.0627134  0.23888649 0.73465569 0.28067086]
 [0.79310147 0.92317072 0.28725206 0.25267597 0.64887397]]
Rows from Index 1 to 2 :
[[0.44730497 0.57359309 0.87743353 0.81901719 0.65695698]
 [0.96623368 0.81135656 0.34887505 0.84605755 0.56605387]]


In [0]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print("====")
print(Z[Z[:,1].argsort()])
 


[[5 4 8]
 [5 9 3]
 [4 4 8]]
====
[[5 4 8]
 [4 4 8]
 [5 9 3]]


In [0]:
X = np.random.rand(4,5)
print(X)
print("======")
Y = X - X.mean(axis=1, keepdims=True)
 
print(Y)






[[0.85920071 0.42308073 0.83111046 0.1592896  0.9932989 ]
 [0.70153226 0.86576185 0.11167441 0.66159932 0.20359561]
 [0.72187403 0.43657486 0.77268594 0.89758309 0.50035857]
 [0.5275851  0.72048157 0.40487263 0.87412904 0.63743094]]
[[ 0.20600463 -0.23011535  0.17791438 -0.49390648  0.34010282]
 [ 0.19269957  0.35692916 -0.39715828  0.15276663 -0.30523708]
 [ 0.05605873 -0.22924043  0.10687064  0.23176779 -0.16545673]
 [-0.10531476  0.08758172 -0.22802722  0.24122918  0.00453108]]


pandas


In [18]:
import pandas as pd
z=pd.Series({'a':1,'b':2,'c':3})
z

a    1
b    2
c    3
dtype: int64

In [0]:
index=['b','a']

In [22]:
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",delimiter='|')
data.head()

user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [25]:
import pandas as pd
users=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",delimiter='|')
print(users)
min_age=users['age'].min()
print(min_age)
mean_age=users['age'].mean()
print(mean_age)
frequent_occ=users['occupation'].value_counts().head(1)
print(frequent_occ)

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]
7
34.05196182396607
student    196
Name: occupation, dtype: int64


In [27]:
import pandas as pd
users=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",delimiter='|')
print(users)
min_age=users['age'].min()
print(min_age)
mean_age=users['age'].mean()
print(mean_age)
frequent_occ=users['occupation'].value_counts()
print(frequent_occ)

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]
7
34.05196182396607
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
salesman          12
lawyer     

In [30]:
df=pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})
df+a

a  b   c
0  2  6  10
1  3  7  11
2  4  8  12

In [32]:
df=pd.DataFrame(data=nprandom.randn(3,3),columns=['d','a','b'])

NameError: ignored

In [41]:
import pandas as pd
grocery=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv",delimiter='\t')
print(grocery)
newData=grocery[["item_name","item_price"]]
print(newData)


      order_id  ...  item_price
0            1  ...      $2.39 
1            1  ...      $3.39 
2            1  ...      $3.39 
3            1  ...      $2.39 
4            2  ...     $16.98 
...        ...  ...         ...
4617      1833  ...     $11.75 
4618      1833  ...     $11.75 
4619      1834  ...     $11.25 
4620      1834  ...      $8.75 
4621      1834  ...      $8.75 

[4622 rows x 5 columns]
                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
...                                     ...        ...
4617                          Steak Burrito    $11.75 
4618                          Steak Burrito    $11.75 
4619                     Chicken Salad Bowl    $11.25 
4620                     Chicken Salad Bo

In [42]:
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv",delimiter='\t')
print(data.head((0))
data=grocery[["item_name","item_price]].drop_duplicates()e


SyntaxError: ignored