**Lab 1**
1. Use git init to create an empty repo
2. Add a file to local repo and push to github
3. Make additional changes to same file, again push to github
4. Add a collaborator to your repo
5. Ask you collaborator to make change to the file and push to repo
6. You try to make a diff change at the same place in the file and push to repo
7. Step6 will fail, Fix merge conflicts and push again
8. Verify all the commits in github
9. Revert code to previous version


**Lab 2**
1. Remove push access to master branch from your collabortator
2. Ask your collaborator to create a new branch
3. Push new code changes to that branch
4. Create a pull request from that branch to master branch
5. Approve and merge the pull request
6. Do a git pull and veirfy that you can see the new changes in master branch


**Lab 3**
1. Use python requests to post a comment on your commit
2. Use python requests to find top 10 commiters on django repo

In [0]:
import requests
r = requests.get("http://www.iitk.ac.in")
print(r.text)
print(r.headers)




<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" dir="ltr" >
  <head>
      <base href="http://www.iitk.ac.in/" />
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="description" content="Globally acclaimed education &amp; research in science, engineering, management &amp; humanities." />
  <title>IIT Kanpur</title>
  <link href="/new/index.php?format=feed&amp;type=rss" rel="alternate" type="application/rss+xml" title="RSS 2.0" />
  <link href="/new/index.php?format=feed&amp;type=atom" rel="alternate" type="application/atom+xml" title="Atom 1.0" />
  <link href="/new/templates/iitk/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />
  <link rel="stylesheet" href="/new/plugins/content/jw_ts/jw_ts/tmpl/Simplistic/css/template.css" type="text/css" />
  <link rel="stylesheet" href="https://www.ii

In [0]:
import requests
import pprint
headers = {'Authorization':'token'}
json = {'body':'comment from api call','path':'index.html'}
r = requests.post('https://api.github.com/repos/renuka019/iitkproj_nov/commits/426d8674e5a08335316722de264e43b2cf7ac705/comments',headers=headers,json=json)
#r = requests.get("http://api.github.com/user/repos",headers=headers)
#print(r.status_code)

pprint.pprint(r.json())

{'author_association': 'OWNER',
 'body': 'comment from api call',
 'commit_id': '426d8674e5a08335316722de264e43b2cf7ac705',
 'created_at': '2019-11-10T09:40:24Z',
 'html_url': 'https://github.com/renuka019/iitkproj_nov/commit/426d8674e5a08335316722de264e43b2cf7ac705#commitcomment-35883107',
 'id': 35883107,
 'line': None,
 'node_id': 'MDEzOkNvbW1pdENvbW1lbnQzNTg4MzEwNw==',
 'path': 'index.html',
 'position': None,
 'updated_at': '2019-11-10T09:40:24Z',
 'url': 'https://api.github.com/repos/renuka019/iitkproj_nov/comments/35883107',
 'user': {'avatar_url': 'https://avatars1.githubusercontent.com/u/57562111?v=4',
          'events_url': 'https://api.github.com/users/renuka019/events{/privacy}',
          'followers_url': 'https://api.github.com/users/renuka019/followers',
          'following_url': 'https://api.github.com/users/renuka019/following{/other_user}',
          'gists_url': 'https://api.github.com/users/renuka019/gists{/gist_id}',
          'gravatar_id': '',
          'html_u

**Lab 4**
1. Create a 8x8x8 array with random values
2. From the matrix in (1) Negate all elements
whose values are between 3 to 8
3. Multiply a 8x3 matrix by 3x2 matrix and
prints the columns as 1 D array

In [0]:
import numpy as np
z = np.random.randint(10,50,(8,8,8))
z

array([[[34, 49, 22, 47, 30, 49, 35, 39],
        [25, 18, 16, 29, 10, 35, 42, 39],
        [29, 30, 45, 23, 33, 32, 34, 30],
        [18, 47, 29, 37, 41, 18, 16, 17],
        [12, 28, 34, 15, 43, 27, 22, 44],
        [23, 19, 17, 22, 13, 28, 43, 41],
        [30, 21, 24, 28, 42, 29, 26, 13],
        [13, 24, 44, 21, 31, 12, 41, 39]],

       [[44, 16, 36, 48, 31, 15, 23, 21],
        [44, 12, 27, 44, 11, 23, 33, 20],
        [15, 29, 19, 32, 23, 45, 26, 16],
        [47, 19, 23, 40, 43, 19, 22, 32],
        [41, 29, 41, 36, 48, 44, 21, 34],
        [17, 15, 23, 12, 32, 32, 22, 17],
        [43, 19, 23, 47, 30, 40, 38, 14],
        [28, 34, 41, 34, 11, 36, 13, 14]],

       [[49, 49, 39, 36, 18, 13, 26, 33],
        [36, 14, 33, 43, 10, 18, 34, 35],
        [36, 18, 37, 38, 14, 10, 11, 49],
        [22, 46, 33, 45, 41, 23, 21, 47],
        [18, 15, 23, 43, 10, 12, 11, 22],
        [25, 18, 39, 27, 38, 47, 30, 38],
        [41, 13, 37, 47, 16, 48, 19, 46],
        [33, 18, 40, 29, 37, 1

In [0]:
import numpy as np
z = np.random.randint(1,10,(8,8,8))
mask =(z>3)&(z<8)
z[mask]=-1*z[mask]
z

array([[[ 2,  2, -7,  2,  1,  1,  1,  8],
        [ 8,  2, -4,  8, -5, -6,  2,  8],
        [-4, -6, -4,  3, -7, -7,  3, -6],
        [ 9, -4, -4,  3,  2,  8, -5,  3],
        [ 8,  8, -6,  8,  2, -4, -7, -4],
        [-4, -7, -7,  1,  3, -7, -4,  2],
        [ 8, -7,  9, -4, -5,  8, -7, -6],
        [ 1, -7, -5,  9,  9, -5,  2,  1]],

       [[-6,  3,  9, -5,  2, -5,  3,  2],
        [-5, -7,  3,  9, -7,  8, -5, -5],
        [-5,  1,  8,  8,  2, -6,  8, -6],
        [-4,  9, -6, -4, -5,  8, -4,  8],
        [-5,  9, -7,  1,  1,  1, -7,  8],
        [ 9,  8,  9, -5,  1, -5, -4, -6],
        [-6, -7,  9,  2,  3, -4,  3, -6],
        [ 3, -6,  2,  2, -5, -4, -5, -4]],

       [[-6, -5, -7, -6, -5,  3, -7, -6],
        [ 1,  9, -5,  1,  9, -6,  2, -5],
        [-7, -6,  2, -5,  3,  2,  9,  2],
        [-6, -7,  3,  2, -5,  1,  1, -5],
        [-5, -7,  3, -6, -5,  3, -5,  1],
        [ 1, -4,  8,  8, -5,  8,  8,  2],
        [-4, -5, -7,  2,  3, -7,  8,  3],
        [-5, -5, -7, -6,  9,  

In [0]:

n=np.random.randint(1,10,(8,3))

m=np.random.randint(1,10,(3,2))
c=np.dot(n,m)
d=c.reshape(1,16)
d


array([[ 91,  44, 114,  73,  71,  94,  73,  54,  83,  90, 103, 108,  84,
         53,  66,  52]])

**Lab 5**

1. Create a 8x8x8 matrix with random values ranging from 5 to 9
2. Find the diagonal of product of two random 5x5 matrices
3. Negate a boolean, or to change the the sign of the float inplace

In [17]:
import numpy as np
n=np.random.randint(1,10,(5,5))

m=np.random.randint(1,10,(5,5))

c=np.dot(n,m)
c


array([[142, 176, 163, 182, 189],
       [108, 147, 132, 156, 129],
       [138, 173, 159, 174, 180],
       [142, 149, 139, 166, 180],
       [114, 139, 126, 170, 153]])

In [9]:
x = np.diag(c)
x


array([350, 338, 320, 338, 336, 333, 321, 377])

In [10]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.1127043 ,  0.19357844,  0.57616079, -0.46248721,  0.12194761,
        0.01113528,  0.47686306, -0.43050413,  0.72075941, -0.68749837,
       -0.55972457,  0.95854727,  0.02210046, -0.24067755, -0.31374429,
       -0.41559698,  0.93373626, -0.71736895, -0.8080628 ,  0.38920265,
        0.80929174,  0.15887012, -0.13334506, -0.87367937,  0.77753387,
        0.62756445,  0.55894228,  0.49194527,  0.97412999,  0.47986612,
        0.08706321, -0.64248188,  0.46513592, -0.52959637, -0.00624204,
        0.5412021 ,  0.99106078, -0.0167502 , -0.59441465, -0.85504218,
       -0.88446399, -0.52019356, -0.19020295,  0.53915792, -0.62896994,
        0.70631863, -0.76714128,  0.413453  ,  0.08867575,  0.48568577,
       -0.62381683,  0.95273449, -0.79830369,  0.27388025,  0.11110883,
        0.23409661, -0.18176734,  0.32584665,  0.10816227, -0.52362178,
       -0.68301727,  0.21522723, -0.82191362,  0.40448073, -0.96910608,
       -0.82786413,  0.69353782, -0.73830534,  0.76908131, -0.40

**Lab 6**

Given 100 random points in 2D space and find the top 10 closest points to the origin.

In [0]:
import numpy as np
z = np.random.randn(100,2)
np.flip(z[np.argsort(np.sqrt(np.sum(z*z,axis=1)))],axis=0)[0:10]

array([[-1.65713132, -2.62991557],
       [ 0.59364159, -2.79935771],
       [ 1.42353489, -2.45224414],
       [ 1.64603875,  2.22817226],
       [-1.75132612,  2.12255773],
       [-2.17604288, -1.68375182],
       [ 2.28296588,  1.46912157],
       [-0.43094484, -2.36098824],
       [-0.95318766, -2.13630145],
       [-1.89568687,  1.32408924]])

In [0]:
z[np.argsort(np.sqrt(np.sum(z*z,axis=1)))]

array([[-0.05739111, -0.05870835],
       [ 0.12891942, -0.02067981],
       [-0.17692062, -0.07792551],
       [-0.21363196, -0.02647346],
       [ 0.15413815, -0.17709961],
       [-0.1975125 , -0.31593855],
       [-0.26508963,  0.31248165],
       [ 0.32450265, -0.27854279],
       [-0.05149669, -0.45200623],
       [ 0.12615399,  0.47446317],
       [ 0.00832938,  0.50156772],
       [-0.0426593 , -0.53493601],
       [-0.29838658, -0.45907052],
       [ 0.09381955, -0.5490729 ],
       [-0.47799091,  0.28636609],
       [ 0.29307113,  0.53319519],
       [-0.26839088,  0.55183425],
       [-0.60692193, -0.153711  ],
       [-0.45356012, -0.43570463],
       [ 0.61351414,  0.16697739],
       [-0.17336681,  0.66088558],
       [ 0.52453106, -0.47363006],
       [-0.4990562 ,  0.51950745],
       [-0.54002176,  0.4938122 ],
       [-0.44485271, -0.58602304],
       [-0.41023337,  0.62386838],
       [ 0.71237956, -0.24474297],
       [ 0.68733922,  0.31171904],
       [ 0.00699111,

**Lab 7**

Find the value of pi using Monte Carlo simulation.

**Hint:-** 

Consider a unit circle which is enclosed in a square. randomly genrate uniformily distributed points inside the square. The fraction of points falling inside the circle is pi/4. 

In [0]:
from numpy import random,sqrt,pi
n=1000000
p=random.rand(n,2)
idx = sqrt(p[:,0]**2+p[:,1]**2)<1
print(sum(idx)/n*4,'result')

print(pi,'real pi')

3.143168 result
3.141592653589793 real pi


**Home Work**

1. wap the first two rows of a random 5x5
array
2. How to get the block-sum of a 16x16 matrix
(block size is 4x4)?
3. Sort an array by the nth column
4. Subtract the mean of each row of a matrix
from each element

In [15]:
import numpy as np
z = np.random.random((5,5))
z

array([[0.6236912 , 0.26090634, 0.1606082 , 0.31317555, 0.76136104],
       [0.78799451, 0.40661979, 0.43736533, 0.76518038, 0.40142898],
       [0.42092807, 0.7533418 , 0.015115  , 0.76040926, 0.6540492 ],
       [0.07491384, 0.49340713, 0.85882899, 0.68218566, 0.80541066],
       [0.8326541 , 0.75154352, 0.00431779, 0.24607623, 0.92586838]])

In [11]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [12]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 2 3]
 [8 5 9]
 [5 8 7]]
[[5 2 3]
 [8 5 9]
 [5 8 7]]


In [13]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
Y


array([[-1.24895616e-01, -1.77125925e-01, -3.52821079e-02,
         8.32177625e-02,  3.39796852e-01,  1.74612828e-01,
        -4.67154279e-02, -3.50094705e-01,  2.00427688e-01,
        -6.39413497e-02],
       [-2.27707723e-01, -5.15348004e-01,  3.81935708e-01,
         4.11378453e-01,  3.51630244e-01, -4.11097694e-01,
        -1.55241047e-01, -6.60509408e-02,  2.30573002e-01,
        -7.19990548e-05],
       [ 1.85758845e-01, -2.83058707e-01, -9.36395507e-02,
         1.15354838e-01,  1.57644863e-02, -2.43079651e-01,
        -3.11220392e-02, -1.56504417e-02,  2.02225814e-01,
         1.47446406e-01],
       [ 3.41702231e-01,  1.64286639e-02, -4.08436873e-01,
         1.28475172e-01, -1.08413986e-01,  4.13240492e-01,
        -4.30710872e-01,  4.47020683e-02,  3.46191631e-01,
        -3.43178527e-01],
       [ 2.71087931e-02,  4.08037284e-01, -4.54667229e-03,
         1.00567848e-01, -3.32025771e-01,  2.98228101e-01,
        -3.65898757e-01,  2.46462118e-01, -3.93983755e-01,
         1.