**Lab 1**
1. Use git init to create an empty repo
2. Add a file to local repo and push to github
3. Make additional changes to same file, again push to github
4. Add a collaborator to your repo
5. Ask you collaborator to make change to the file and push to repo
6. You try to make a diff change at the same place in the file and push to repo
7. Step6 will fail, Fix merge conflicts and push again
8. Verify all the commits in github
9. Revert code to previous version


https://github.com/shekhariet/tanushree/settings/collaboration 

**Lab 2**
1. Remove push access to master branch from your collabortator
2. Ask your collaborator to create a new branch
3. Push new code changes to that branch
4. Create a pull request from that branch to master branch
5. Approve and merge the pull request
6. Do a git pull and veirfy that you can see the new changes in master branch


**Lab 3**
1. Use python requests to post a comment on your commit
2. Use python requests to find top 10 commiters on django repo

In [0]:
#Use python requests to post a comment on your commit
import requests
import pprint
headers={'Authorization': 'token c979e92d2f783a8a6bc6ec76e2982bfa19b13a4c'}
json={'body':'commit for api call good','path':'index.html'}
r=requests.post('http://api.github.com/user/repos/shekhariet@yahoo.co.in/SHEKHAR_IITK/commits/deb8b47b20d3fbfbc695c498c997415429f1f316/comments',headers=headers,json=json)
print(r.status_code)
pprint.pprint(r.json())

404
{'documentation_url': 'https://developer.github.com/v3', 'message': 'Not Found'}


**Lab 4**
1. Create a 8x8x8 array with random values
2. From the matrix in (1) Negate all elements
whose values are between 3 to 8
3. Multiply a 8x3 matrix by 3x2 matrix and
prints the columns as 1 D array

In [0]:
#Create a 8x8x8 array with random values
import numpy as np
z=np.random.randint(1,10,(8,8,8))
print('8x8x8 matrix generated-----',z)


8x8x8 matrix generated----- [[[6 1 6 7 9 9 6 9]
  [4 9 6 8 3 1 9 7]
  [1 3 9 7 8 5 5 4]
  [2 3 8 1 8 2 9 1]
  [6 1 1 2 6 5 9 6]
  [2 1 2 8 8 5 2 6]
  [3 9 2 9 5 5 6 7]
  [1 9 5 1 9 1 5 9]]

 [[9 3 7 4 5 7 6 8]
  [9 2 8 6 6 8 9 2]
  [2 7 4 4 9 2 4 6]
  [3 7 3 2 5 9 4 2]
  [3 4 2 1 2 5 3 3]
  [8 7 4 2 5 5 3 1]
  [1 1 3 3 4 8 9 3]
  [3 8 2 3 8 3 9 6]]

 [[2 3 3 5 5 3 2 8]
  [2 5 7 8 8 7 5 6]
  [6 7 3 3 8 6 9 6]
  [9 7 2 4 1 8 4 5]
  [7 9 7 1 4 4 7 4]
  [8 7 9 4 6 3 9 1]
  [2 2 5 9 5 7 3 1]
  [8 6 4 2 5 5 3 9]]

 [[4 5 5 2 3 7 1 7]
  [1 2 5 2 6 8 2 6]
  [3 9 5 6 6 2 2 6]
  [4 2 8 3 8 5 4 1]
  [8 3 5 5 5 9 5 8]
  [8 9 7 4 6 6 5 3]
  [9 7 3 8 5 1 3 3]
  [9 8 9 9 1 6 5 5]]

 [[7 4 9 3 7 5 6 6]
  [3 8 6 7 3 6 3 6]
  [4 5 7 9 9 6 6 4]
  [7 4 4 3 6 3 9 2]
  [4 2 7 3 9 9 3 8]
  [7 3 8 1 6 7 1 6]
  [2 1 6 8 5 7 1 3]
  [6 5 5 8 9 1 6 1]]

 [[6 5 2 1 9 9 7 8]
  [6 1 9 6 6 1 5 9]
  [1 6 9 1 4 7 2 4]
  [3 1 3 8 1 7 2 3]
  [7 9 8 1 5 4 9 9]
  [4 2 2 5 8 5 3 7]
  [5 2 1 8 6 4 5 7]
  [4 3 5 9 4 2 8 5]]



In [0]:
#From the matrix in (1) Negate all elements whose values are between 3 to 8
import numpy as np
z=np.random.randint(1,10,(8,8,8))
mask=(z>3) & (z<8)
z[mask]=-1*z[mask]
z

array([[[ 1,  8,  1, -7, -6, -4,  3,  1],
        [ 3,  3,  3, -6,  9,  3, -5,  1],
        [ 9,  9, -7,  9, -4, -7,  2,  8],
        [ 1,  2, -5,  9, -5,  2,  1, -4],
        [-4,  8,  9,  3,  2, -6,  9,  8],
        [-6, -4, -7, -5, -6, -4,  2, -5],
        [ 2, -7,  2,  9, -6, -5,  1,  3],
        [ 3, -7,  8,  3, -4, -6,  1, -5]],

       [[ 3, -4, -5,  1, -5,  9, -7, -6],
        [ 2,  3, -4,  3, -5,  9,  8,  9],
        [ 3, -7, -5,  2, -6,  3,  8,  8],
        [-4,  1,  9, -5,  1, -4,  3, -7],
        [-6, -6,  3,  8,  9,  2, -4,  2],
        [-5,  2,  9,  1,  3, -6,  2,  1],
        [ 9, -5,  9,  8, -7,  3,  3,  1],
        [-6, -4,  1,  1,  3,  9,  3,  2]],

       [[ 1, -7,  8,  3, -7, -4,  3,  3],
        [-5, -6,  8,  8, -5,  1, -5,  8],
        [ 3,  8,  2,  2,  9,  8,  9,  3],
        [-5, -6, -4,  8, -5,  3,  1,  9],
        [ 2,  1,  2, -6,  3, -7,  8, -7],
        [-7,  1,  9, -7, -4,  1, -6, -6],
        [ 3,  2,  1,  1, -5,  3, -7, -4],
        [-6,  3, -4, -6, -6,  

In [3]:
#Multiply a 8x3 matrix by 3x2 matrix and prints the columns as 1 D array
import numpy as np   
x = np.random.randint(1,10,(8,3))
y = np.random.randint(1,10,(3,2))
res = np.dot(x,y) 
#print(res)
# print resulted matrix 
res[:,0]

array([ 95, 117,  88,  35,  75,  92, 107, 106])

**Lab 5**

1. Create a 8x8x8 matrix with random values ranging from 5 to 9
2. Find the diagonal of product of two random 5x5 matrices
3. Negate a boolean, or to change the the sign of the float inplace

In [4]:
import numpy as np
x=[1,2,3,4]
z=np.array(x)
z=np.random.randint( 5, 9, (8,8,8))
z

array([[[8, 7, 7, 8, 6, 7, 7, 7],
        [6, 5, 6, 6, 5, 8, 7, 7],
        [5, 5, 5, 6, 8, 5, 6, 8],
        [8, 7, 8, 5, 6, 5, 5, 5],
        [8, 5, 8, 8, 5, 8, 7, 6],
        [7, 7, 6, 8, 7, 7, 5, 8],
        [5, 6, 5, 8, 7, 5, 7, 5],
        [5, 5, 6, 6, 6, 8, 8, 6]],

       [[6, 8, 8, 5, 5, 5, 8, 5],
        [6, 5, 7, 6, 5, 5, 5, 8],
        [7, 5, 5, 6, 6, 5, 5, 7],
        [8, 8, 6, 5, 6, 8, 6, 8],
        [7, 7, 7, 7, 7, 7, 6, 6],
        [8, 5, 7, 5, 8, 6, 7, 7],
        [7, 8, 8, 8, 5, 8, 6, 6],
        [6, 6, 8, 7, 7, 5, 8, 7]],

       [[7, 8, 6, 5, 5, 7, 6, 7],
        [5, 5, 7, 7, 8, 5, 7, 7],
        [8, 5, 5, 6, 7, 6, 8, 8],
        [8, 8, 8, 5, 6, 8, 7, 8],
        [8, 5, 6, 8, 7, 5, 8, 7],
        [6, 8, 5, 5, 5, 7, 5, 6],
        [6, 6, 7, 7, 7, 8, 8, 8],
        [7, 5, 7, 6, 8, 6, 6, 8]],

       [[5, 7, 8, 5, 7, 6, 8, 5],
        [8, 6, 6, 6, 6, 6, 6, 7],
        [5, 8, 6, 8, 8, 6, 6, 5],
        [8, 5, 5, 7, 5, 5, 6, 6],
        [6, 5, 5, 5, 5, 5, 8, 8],
        

In [9]:
#Find the diagonal of product of two random 5x5 matrices
A = np.random.uniform(0,2,(5,5))
B = np.random.uniform(0,2,(5,5))
print('final result.......')
np.sum(A * B.T, axis=1)

final result.......


array([3.33194784, 5.42020901, 2.99641201, 6.70137796, 1.52998404])

In [13]:
#3.	Negate a boolean, or to change the the sign of the float inplace
d= np.random.uniform(-1.0,1.0,10)
print(d)
t=np.negative(d, out=d)
print('final result.......')
print(t)

[ 0.24007963  0.06083579  0.01581629 -0.60812854  0.85501499  0.82904208
  0.70970756 -0.20793929 -0.20169721  0.38202687]
final result.......
[-0.24007963 -0.06083579 -0.01581629  0.60812854 -0.85501499 -0.82904208
 -0.70970756  0.20793929  0.20169721 -0.38202687]


**Lab 6**

Given 100 random points in 2D space and find the top 10 closest points to the origin.

In [0]:
import numpy as np
#z=np.random.randint(1,10,(100,2))
z=np.random.rand(100,2)
#np.flip(z[np.argsort(np.sort(np.sum(z*z)))],axis=0)[0:10]
z[np.argsort(np.sort(np.sum(z*z,axis=1)))]
#z.shape

array([[0.73724339, 0.22901078],
       [0.09987485, 0.69028552],
       [0.30161647, 0.28229311],
       [0.24667722, 0.34285909],
       [0.85725003, 0.2376511 ],
       [0.2781224 , 0.81448074],
       [0.6954938 , 0.75120625],
       [0.47119281, 0.29120685],
       [0.89903511, 0.12958408],
       [0.82831173, 0.08259601],
       [0.85171948, 0.11396336],
       [0.85845895, 0.62795151],
       [0.53806836, 0.65280337],
       [0.36449537, 0.81524807],
       [0.88797816, 0.95303282],
       [0.86162058, 0.31732195],
       [0.58716422, 0.26600751],
       [0.41250231, 0.25628632],
       [0.49695579, 0.26703141],
       [0.82669917, 0.00250212],
       [0.95000151, 0.2702066 ],
       [0.0088073 , 0.55040016],
       [0.12041982, 0.8915417 ],
       [0.61533534, 0.23354765],
       [0.90795097, 0.61871271],
       [0.89077553, 0.67561912],
       [0.28343964, 0.14700852],
       [0.97570024, 0.12005573],
       [0.86133532, 0.23338946],
       [0.2878185 , 0.5090419 ],
       [0.

**Lab 7**

Find the value of pi using Monte Carlo simulation.

**Hint:-** 

Consider a unit circle which is enclosed in a square. randomly genrate uniformily distributed points inside the square. The fraction of points falling inside the circle is pi/4. 

In [0]:
import numpy as np
coordinates=np.random.randn(100,2)
dist=np.sqrt(coordinates[:,0]**2+coordinates[:,1]**2)
top_10=np.argsort(dist)[:10]
print(coordinates[top_10])

[[ 0.13787115 -0.01376572]
 [-0.13291018 -0.10240872]
 [ 0.06864681  0.23861821]
 [ 0.25921538 -0.051134  ]
 [ 0.34205793 -0.09113048]
 [ 0.23293628  0.31756895]
 [-0.33554449 -0.21755877]
 [-0.0090765  -0.40841561]
 [ 0.34017512  0.24400036]
 [ 0.05807503 -0.46108587]]


**Home Work**

1. wap the first two rows of a random 5x5
array
2. How to get the block-sum of a 16x16 matrix
(block size is 4x4)?
3. Sort an array by the nth column
4. Subtract the mean of each row of a matrix
from each element