**Lab 1**
1. Use git init to create an empty repo
2. Add a file to local repo and push to github
3. Make additional changes to same file, again push to github
4. Add a collaborator to your repo
5. Ask you collaborator to make change to the file and push to repo
6. You try to make a diff change at the same place in the file and push to repo
7. Step6 will fail, Fix merge conflicts and push again
8. Verify all the commits in github
9. Revert code to previous version


**Lab 2**
1. Remove push access to master branch from your collabortator
2. Ask your collaborator to create a new branch
3. Push new code changes to that branch
4. Create a pull request from that branch to master branch
5. Approve and merge the pull request
6. Do a git pull and veirfy that you can see the new changes in master branch


**Lab 3**
1. Use python requests to post a comment on your commit
2. Use python requests to find top 10 commiters on django repo

In [0]:
import requests
import pprint
headers={'Authorization':'token '}
json={'body':'comment from api call','path':'index.html'}
r=requests.post('https://api.github.com/repos/trilokamethi/trilok123/commits/f38955f13a8c4b0a96e3db2440165fc381c0f516/comments',headers=headers,json=json)
pprint.pprint(r.json())


{'author_association': 'OWNER',
 'body': 'comment from api call',
 'commit_id': 'f38955f13a8c4b0a96e3db2440165fc381c0f516',
 'created_at': '2019-11-10T09:36:34Z',
 'html_url': 'https://github.com/trilokamethi/trilok123/commit/f38955f13a8c4b0a96e3db2440165fc381c0f516#commitcomment-35883080',
 'id': 35883080,
 'line': None,
 'node_id': 'MDEzOkNvbW1pdENvbW1lbnQzNTg4MzA4MA==',
 'path': 'index.html',
 'position': None,
 'updated_at': '2019-11-10T09:36:34Z',
 'url': 'https://api.github.com/repos/trilokamethi/trilok123/comments/35883080',
 'user': {'avatar_url': 'https://avatars3.githubusercontent.com/u/57561850?v=4',
          'events_url': 'https://api.github.com/users/trilokamethi/events{/privacy}',
          'followers_url': 'https://api.github.com/users/trilokamethi/followers',
          'following_url': 'https://api.github.com/users/trilokamethi/following{/other_user}',
          'gists_url': 'https://api.github.com/users/trilokamethi/gists{/gist_id}',
          'gravatar_id': '',
     

**Lab 4**
1. Create a 8x8x8 array with random values
2. From the matrix in (1) Negate all elements
whose values are between 3 to 8
3. Multiply a 8x3 matrix by 3x2 matrix and
prints the columns as 1 D array

Solution Lab 4.1

In [0]:
import numpy as np
x = np.random.random((8,8,8))
print(x)

[[[0.84674966 0.25698532 0.96221171]
  [0.99026396 0.79428097 0.0443547 ]
  [0.02447031 0.05846575 0.81424578]]

 [[0.79354338 0.76280785 0.55624433]
  [0.27586619 0.56208477 0.37276576]
  [0.76786982 0.68917669 0.53808756]]

 [[0.8986954  0.25369561 0.56288234]
  [0.39570467 0.5912981  0.59216438]
  [0.60754917 0.43268704 0.6308273 ]]]


Solution Lab 4.2

In [0]:
import numpy as np
a = np.random.randint(1,10,(8,8,8))
print(a)
mask=(a>3)&(a<8)
a[mask]=-1*a[mask]
print(a)

[[[8 2 7 2 6 1 6 7]
  [4 3 1 1 6 4 7 1]
  [7 9 8 3 7 9 5 7]
  [1 1 8 5 1 5 8 9]
  [9 2 8 9 9 5 1 7]
  [2 3 1 8 5 6 7 5]
  [8 5 9 1 9 4 6 3]
  [9 5 7 9 1 4 8 7]]

 [[4 4 1 8 4 7 3 6]
  [5 8 9 6 2 7 4 1]
  [1 5 9 5 2 1 3 5]
  [9 1 6 6 5 9 5 4]
  [3 5 1 2 9 9 6 4]
  [8 2 3 1 3 1 5 1]
  [1 7 9 7 4 8 5 9]
  [4 3 7 8 7 9 8 2]]

 [[9 6 6 3 7 2 8 4]
  [7 6 9 5 9 8 5 6]
  [1 8 5 8 6 5 8 5]
  [3 4 6 1 1 4 3 3]
  [4 8 8 4 9 2 8 5]
  [2 8 6 8 5 5 9 2]
  [2 9 5 9 4 7 1 1]
  [1 3 9 6 9 6 7 1]]

 [[9 1 2 7 4 4 5 3]
  [3 5 4 5 1 2 6 6]
  [5 4 8 4 5 1 9 8]
  [9 1 3 9 2 3 2 4]
  [7 3 1 8 1 4 5 6]
  [3 1 2 4 2 2 8 8]
  [4 3 2 5 4 7 2 8]
  [1 6 1 9 3 6 9 2]]

 [[9 1 5 5 3 2 6 4]
  [1 7 1 7 3 5 8 1]
  [2 2 7 9 2 1 4 6]
  [1 8 8 3 3 6 9 6]
  [5 7 2 8 6 2 8 1]
  [9 2 2 4 3 2 6 3]
  [1 3 8 4 6 6 7 2]
  [3 9 3 7 3 8 2 1]]

 [[3 4 8 6 5 5 4 9]
  [4 2 7 2 2 6 2 2]
  [7 8 8 1 9 1 6 7]
  [4 7 1 3 6 5 1 7]
  [1 2 7 9 5 2 7 7]
  [7 5 6 5 2 9 1 8]
  [9 2 7 4 9 2 8 4]
  [6 3 8 3 4 6 3 4]]

 [[8 9 7 5 9 6 7 2]
  [3 6 3

Solution 4.3


In [0]:
import numpy as np
a = np.random.randint(1,10,(8,3))
b = np.random.randint(1,10,(3,2))
c=np.dot(a,b)
print(c)
d=c.reshape(1,16)
print(d)

[[ 83  43]
 [ 42  36]
 [108  70]
 [ 52  38]
 [ 74  48]
 [ 78  60]
 [ 88  78]
 [142 104]]
[[ 83  43  42  36 108  70  52  38  74  48  78  60  88  78 142 104]]


**Lab 5**

1. Create a 8x8x8 matrix with random values ranging from 5 to 9
2. Find the diagonal of product of two random 5x5 matrices
3. Negate a boolean, or to change the the sign of the float inplace

Solution 5.1

In [0]:
import numpy as np
a = np.random.randint(5,9,(8,8,8))
print(a)

[[[6 5 5 7 7 5 6 5]
  [6 8 6 7 8 6 7 6]
  [5 6 7 8 5 7 6 7]
  [5 7 6 8 7 5 8 7]
  [7 5 6 8 8 5 7 6]
  [5 8 8 5 7 7 5 6]
  [8 8 6 5 6 5 7 8]
  [7 6 6 5 6 7 8 5]]

 [[8 7 7 5 8 7 6 8]
  [6 6 5 5 5 7 7 6]
  [5 5 5 6 6 7 5 8]
  [6 7 5 5 8 7 7 6]
  [7 8 5 6 7 6 7 6]
  [5 5 5 7 5 5 8 5]
  [6 5 5 5 5 7 8 7]
  [6 7 5 8 7 6 5 6]]

 [[7 7 6 6 7 8 8 6]
  [5 5 7 7 8 8 6 8]
  [7 8 6 6 5 7 7 5]
  [8 7 8 8 8 5 5 8]
  [6 8 8 5 6 5 6 6]
  [7 8 5 6 8 7 6 7]
  [6 6 7 8 8 8 5 5]
  [8 6 5 5 5 8 5 6]]

 [[5 5 7 5 8 5 6 5]
  [5 7 8 7 8 5 8 7]
  [7 7 5 6 8 7 8 8]
  [6 5 5 8 7 8 8 6]
  [6 5 8 5 5 5 7 8]
  [6 8 6 7 7 8 5 7]
  [5 8 8 7 6 8 7 8]
  [5 6 5 8 5 8 6 7]]

 [[7 6 6 8 6 6 6 7]
  [7 6 6 6 6 6 5 8]
  [6 6 7 6 8 7 5 6]
  [8 6 5 7 5 8 7 8]
  [8 6 6 8 5 8 7 8]
  [5 7 5 6 5 7 7 6]
  [7 5 6 5 5 8 5 7]
  [6 7 8 6 8 6 5 7]]

 [[8 5 6 5 8 7 6 7]
  [8 5 7 7 7 8 8 5]
  [8 8 5 6 8 6 8 6]
  [8 6 5 6 8 8 6 5]
  [5 6 5 5 7 6 8 7]
  [6 5 5 8 7 5 5 8]
  [7 8 6 6 5 8 5 6]
  [7 7 8 5 7 5 7 5]]

 [[8 5 7 5 7 8 6 5]
  [5 8 6

Solution 5.2

In [0]:
import numpy as np


Solution 5.3

In [0]:
import numpy as np


**Lab 6**

Given 100 random points in 2D space and find the top 10 closest points to the origin.

In [0]:
import numpy as np
z=np.random.randn(100,2)
np.flip(z[np.argsort(np.sqrt(np.sum(z*z,axis=1)))],axis=0)[0:10]

array([[-5.51036904e-01,  3.39294829e+00],
       [ 1.90764265e+00,  1.79123095e+00],
       [-1.91512304e+00,  1.69479332e+00],
       [ 7.35312410e-01,  2.33408448e+00],
       [ 1.46299535e+00,  1.81832254e+00],
       [ 1.90224875e+00,  1.26871826e+00],
       [ 5.91014601e-01, -2.14265043e+00],
       [ 9.61069346e-01,  2.00220920e+00],
       [ 2.20475742e+00,  2.96482767e-03],
       [ 1.37948548e+00,  1.71848400e+00]])

**Lab 7**

Find the value of pi using Monte Carlo simulation.

**Hint:-** 

Consider a unit circle which is enclosed in a square. randomly genrate uniformily distributed points inside the square. The fraction of points falling inside the circle is pi/4. 

In [1]:
from pylab import plot,show,axis
from numpy import random,sqrt,pi

n = 1000000
p = random.rand(n,2)

idx = sqrt(p[:,0]**2+p[:,1]**2) < 1


print('%0.16f' % (sum(idx).astype('double')/n*4),'result')
print ('%0.16f' % pi,'real pi')

3.1411519999999999 result
3.1415926535897931 real pi


**Home Work**

1. wap the first two rows of a random 5x5
array
2. How to get the block-sum of a 16x16 matrix
(block size is 4x4)?
3. Sort an array by the nth column
4. Subtract the mean of each row of a matrix
from each element