**Lab 1**
1. Use git init to create an empty repo
2. Add a file to local repo and push to github
3. Make additional changes to same file, again push to github
4. Add a collaborator to your repo
5. Ask you collaborator to make change to the file and push to repo
6. You try to make a diff change at the same place in the file and push to repo
7. Step6 will fail, Fix merge conflicts and push again
8. Verify all the commits in github
9. Revert code to previous version


**Lab 2**
1. Remove push access to master branch from your collabortator
2. Ask your collaborator to create a new branch
3. Push new code changes to that branch
4. Create a pull request from that branch to master branch
5. Approve and merge the pull request
6. Do a git pull and veirfy that you can see the new changes in master branch


**Lab 3**
1. Use python requests to post a comment on your commit
2. Use python requests to find top 10 commiters on django repo

**Lab 4**
1. Create a 8x8x8 array with random values
2. From the matrix in (1) Negate all elements
whose values are between 3 to 8
3. Multiply a 8x3 matrix by 3x2 matrix and
prints the columns as 1 D array

In [0]:
import numpy as np
z=np.random.randn(8,8,8)
z

In [0]:
import numpy as np
z=np.random.randn(8,8,8)
a1=(z>3) & (z<8)
z[a1]*=-1
print(z)


In [0]:
import numpy as np
z1=np.random.randint(5,9,(8,3))
z2=np.random.randint(3,6,(3,2))
z3=np.dot(z1,z2)
z3.reshape(1,16)


array([[83, 74, 95, 88, 89, 87, 88, 77, 69, 64, 82, 78, 91, 84, 87, 80]])

**Lab 5**

1. Create a 8x8x8 matrix with random values ranging from 5 to 9
2. Find the diagonal of product of two random 5x5 matrices
3. Negate a boolean, or to change the the sign of the float inplace

In [0]:
import numpy as np
z=np.random.randint(5,9,(8,8,8))
z


In [0]:
import numpy as np
z1=np.random.randint(5,9,(5,5))
print(z1)
z2=np.random.randint(3,6,(5,5))
print(z2)
z3=np.matmul(z1,z2)
np.diagonal(z3)

[[7 8 7 6 8]
 [7 7 6 5 7]
 [7 5 6 8 5]
 [8 7 7 5 6]
 [7 7 6 5 7]]
[[3 5 3 5 5]
 [5 5 5 4 4]
 [4 4 3 5 3]
 [3 5 4 5 3]
 [5 5 3 4 5]]


array([147, 154, 111, 152, 131])

**Lab 6**

Given 100 random points in 2D space and find the top 10 closest points to the origin.

In [0]:
import numpy as np
z=np.random.randn(100,2) 
z1=np.sum(z*z,axis=1)
z2=np.argsort(z1)
z[z2]


In [0]:
dist=np.sqrt(z[:,0]**2+z[:,1]**2)
z2=np.argsort(dist)
z[z2]


**Lab 7**

Find the value of pi using Monte Carlo simulation.

**Hint:-** 

Consider a unit circle which is enclosed in a square. randomly genrate uniformily distributed points inside the square. The fraction of points falling inside the circle is pi/4. 

In [19]:
import random as r
import math as m
# Number of darts that land inside.
inside = 0
# Total number of darts to throw.
total = 405000
# Iterate for the number of darts.
for i in range(0, total):
  # Generate random x, y in [0, 1].
  x2 = r.random()**2
  y2 = r.random()**2
    # Increment if inside unit circle.
  if m.sqrt(x2 + y2) < 1.0:
    inside += 1
# inside / total = pi / 4
pi = (float(inside) / total) * 4

# It works!
print(pi)

3.138587654320988


**Home Work**

1. wap the first two rows of a random 5x5
array
2. How to get the block-sum of a 16x16 matrix
(block size is 4x4)?
3. Sort an array by the nth column
4. Subtract the mean of each row of a matrix
from each element

In [0]:
import numpy as np
z=np.random.randint(3,5,(5,5)) 
print(z[:2])


In [38]:
import numpy as np
z=np.random.randint(3,9,(16,16)) 
z1=np.sum(z,axis((0,3))

SyntaxError: ignored

In [0]:
import requests
r=requests.get('https://api.github.com/user/repos/')
print(r.status_code)

404


In [0]:
import requests
import pprint
headers={'Authorization':'788b89d268f7071eefe91ecfbe338c3a3bff036a'}
r=requests.get('https://api.github.com/users/repos', headers=headers)
pprint.pprint(r.json())

{'avatar_url': 'https://avatars0.githubusercontent.com/u/77416?v=4',
 'bio': None,
 'blog': '',
 'company': None,
 'created_at': '2009-04-24T13:53:27Z',
 'email': None,
 'events_url': 'https://api.github.com/users/repos/events{/privacy}',
 'followers': 19,
 'followers_url': 'https://api.github.com/users/repos/followers',
 'following': 0,
 'following_url': 'https://api.github.com/users/repos/following{/other_user}',
 'gists_url': 'https://api.github.com/users/repos/gists{/gist_id}',
 'gravatar_id': '',
 'hireable': None,
 'html_url': 'https://github.com/repos',
 'id': 77416,
 'location': None,
 'login': 'repos',
 'name': None,
 'node_id': 'MDQ6VXNlcjc3NDE2',
 'organizations_url': 'https://api.github.com/users/repos/orgs',
 'public_gists': 0,
 'public_repos': 0,
 'received_events_url': 'https://api.github.com/users/repos/received_events',
 'repos_url': 'https://api.github.com/users/repos/repos',
 'site_admin': False,
 'starred_url': 'https://api.github.com/users/repos/starred{/owner}{/re

In [0]:
import requests
import pprint
headers={'Authorization':'token 8a5f460c05363d4c097e45f311d262a2f655d2fb'}
json={'body':'comment from api cell','path':'index.html'}
r=requests.post('https://api.github.com/repos/guptavk76/vv/commits/e5ffbf6e650db3ae6ddf8dabcdfff4193493f199/', headers=headers,json=json)
pprint.pprint(r.json())

JSONDecodeError: ignored

In [0]:
import numpy as np
z=np.random.randn(100,2)
z1=np.sum(z,axis=0)
np.savez('tmp.npz',s=z,s1=z1)

In [0]:
a=np.load('tmp.npz')


In [11]:
a['s1']

array([-12.72853234,  -2.45414443])

In [50]:
import pandas as pd
z=pd.Series({'a':1,'b':2, 'c':3})
z

a    1
b    2
c    3
dtype: int64

In [0]:
import pandas as pd
z=pd.Series({'a':1,'b':2, 'c':3})
z

In [52]:
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object


In [58]:

import pandas as pd
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [59]:
import pandas as pd
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42
